import { colleges, departments } from "../../data/catalog";
import type { ScenarioDef } from "./types";

const college = (slug: string) => `/academics/colleges/${slug}`;
/** Colleges with at least one catalog department get the department list and jump menu. */
const collegesWithDepartments = colleges.filter((c) => departments.some((d) => d.college === c.slug)).map((c) => college(c.slug));

/** Every page built on the academics CMS templates (the catalog and course search are plans 06/07). */
export const cmsPages = [
  "/academics", "/academics/colleges/:slug", "/academics/departments/:slug", "/academics/programs",
  "/academics/programs/:slug", "/academics/minors", "/academics/certificates", "/academics/calendar", "/academics/courses",
  "/faculty", "/faculty/:slug",
];

export const academicsScenarios: ScenarioDef[] = [
  // ---------- Section template (every academics CMS page) ----------
  {
    id: "academics-sidebar-contrast-001",
    rule: "contrast-text-low",
    title: "Academics sidebar links have low contrast",
    description: "The CMS theme colors the sidebar navigation links slate gray (#8c9aa3) on the beige sidebar (#f3f1ea), about 2.6:1.",
    fixDescription: "Uses #606c74, just above the 4.5:1 minimum.",
    pages: cmsPages,
    component: "CmsPage / section sidebar",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "academics-header-contrast-001",
    rule: "contrast-text-low",
    title: "Academics section header has low contrast",
    description: "The large green \"Academics\" section header is gray (#a0a0a0) on the fern-green section bar (#2f5d3a), about 2.92:1, just under the 3:1 minimum for large text.",
    fixDescription: "Uses #a4a4a4, just above the 3:1 minimum.",
    pages: cmsPages,
    component: "UniversityLayout / SectionBar",
    mechanism: "css",
    severity: "serious",
  },

  // ---------- /academics ----------
  {
    id: "academics-hub-card-alt-redundant-001",
    rule: "alt-redundant",
    title: "College card photos repeat the card title",
    description: "Each college card photo has alt text identical to the card title next to it (\"College of Science\"), so screen readers read the name twice.",
    fixDescription: "Marks the photos decorative (alt=\"\") because the title already names the card.",
    pages: ["/academics"],
    component: "AcademicsHub / Card",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- CollegeLanding (/academics/colleges/:slug) ----------
  {
    id: "academics-college-hero-alt-suspicious-001",
    rule: "alt-suspicious",
    title: "College banner photo uses its file name as alt text",
    description: "The banner photo's alt text is the uploaded file name (for example \"college-engineering_banner_v2.jpg\").",
    fixDescription: "Uses alt text that describes the photo.",
    pages: ["/academics/colleges/:slug"],
    component: "CollegeLanding / Hero",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-college-fake-heading-001",
    rule: "heading-possible",
    title: "\"Why study at…\" is a bold paragraph, not a heading",
    description: "The highlights section is introduced by bold paragraph text styled like a heading, so it is missing from the heading outline.",
    fixDescription: "Uses an <h2>.",
    pages: ["/academics/colleges/:slug"],
    component: "CollegeLanding",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-college-dept-link-generic-001",
    rule: "link-generic",
    title: "Department links all say \"Learn more\"",
    description: "Each department summary ends with a \"Learn more\" link, which is meaningless out of context (for example in a screen reader's links list).",
    fixDescription: "Link text names the department: \"Visit the Department of Biology\".",
    pages: collegesWithDepartments,
    component: "CollegeLanding / department list",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-college-jump-select-label-001",
    rule: "select-missing-label",
    title: "\"Jump to\" menu has no label",
    description: "The quick-jump <select> for departments and programs has only a \"-- Select --\" first option and no label.",
    fixDescription: "Adds a visible <label> associated with the select.",
    pages: collegesWithDepartments,
    component: "CollegeLanding / JumpMenu",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "academics-college-video-title-001",
    rule: "iframe-missing-title",
    title: "College video embed has no title",
    description: "The embedded video player's <iframe> has no title attribute, so screen readers announce only \"frame\".",
    fixDescription: "Gives the iframe a title matching the video.",
    // Colleges with a video (collegeVideos in pages/academics/colleges/$slug.tsx).
    pages: [college("engineering"), college("science"), college("health-sciences")],
    component: "CollegeLanding / VideoEmbed",
    mechanism: "markup",
    severity: "serious",
  },

  // ---------- DepartmentPage (/academics/departments/:slug) ----------
  {
    id: "academics-dept-heading-skip-001",
    rule: "heading-skipped",
    title: "Department template jumps from h2 to h4",
    description: "Under \"Academics\" (h2), the Degree Programs and Courses headings are <h4>, skipping h3. The old CMS template hard-codes the smaller heading style.",
    fixDescription: "Uses <h3> for the subsections.",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-dept-photo-alt-001",
    rule: "img-missing-alt",
    title: "Department photo has no alt attribute",
    description: "The photo floated beside the department overview was uploaded without alt text; the img has no alt attribute at all.",
    fixDescription: "Adds alt text describing the photo.",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "academics-dept-course-table-caption-001",
    rule: "table-no-caption",
    title: "Course list table has no caption",
    description: "The department course table is introduced only by a nearby heading; it has no <caption> naming it.",
    fixDescription: "Adds a caption (\"Computer Science courses, 2026–27\").",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage / course table",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-dept-full-color-001",
    rule: "color-only-info",
    title: "Full courses are shown only in red",
    description: "Courses whose Fall 2026 sections are all full are marked only by red text, explained by a legend (\"Courses in red are full\").",
    fixDescription: "Adds a visible \"Full\" label to those courses.",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage / course table",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-dept-document-link-001",
    rule: "link-document",
    title: "PDF links don't say they are PDFs",
    description: "The Documents & Forms links open PDF files but don't mention the file type or size.",
    fixDescription: "Appends \"(PDF, 2 KB)\" to each link.",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage / documents",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- /academics/programs ----------
  {
    id: "academics-programs-college-select-001",
    rule: "select-missing-label",
    title: "College filter has no label",
    description: "The college filter <select> sits next to plain \"College:\" text that is not a <label>.",
    fixDescription: "Turns the text into a <label> for the select.",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "academics-programs-level-fieldset-001",
    rule: "fieldset-missing",
    title: "Degree level radios are not grouped",
    description: "The All / Undergraduate / Graduate radio buttons have no fieldset or legend, so \"Degree level\" is not announced with them.",
    fixDescription: "Wraps the radios in a fieldset with a \"Degree level\" legend.",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-programs-reset-javascript-001",
    rule: "link-javascript",
    title: "\"Reset filters\" is an href=\"#\" link",
    description: "Reset filters is a link to \"#\" with a click handler: it acts as a button but is announced as a link that goes nowhere.",
    fixDescription: "Uses a <button>.",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-programs-count-status-001",
    rule: "sr-status-not-announced",
    title: "Result count changes silently",
    description: "When a filter changes, the \"Showing N programs\" text updates, but it is not a live region, so screen reader users aren't told.",
    fixDescription: "Makes the count a polite status region (role=\"status\").",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "behavior",
    severity: "moderate",
  },
  {
    id: "academics-programs-impacted-color-001",
    rule: "color-only-info",
    title: "Impacted programs are marked by a red dot only",
    description: "Impacted programs have a small red dot next to the name and a legend at the top; the dot has no text alternative.",
    fixDescription: "Replaces the dot with a visible \"Impacted\" label.",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "serious",
  },

  // ---------- ProgramPage (/academics/programs/:slug) ----------
  {
    id: "academics-program-req-table-caption-001",
    rule: "table-no-caption",
    title: "Degree requirements table has no caption",
    description: "The unit requirements table has no <caption>.",
    fixDescription: "Adds a caption naming the degree.",
    pages: ["/academics/programs/:slug"],
    component: "ProgramPage",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- Minors, certificates, calendar ----------
  {
    id: "academics-minors-link-generic-001",
    rule: "link-generic",
    title: "Change of major/minor form link says \"here\"",
    description: "The link to the Change of Major/Minor form reads just \"here\".",
    fixDescription: "Link text names where the form is: \"from the Office of the Registrar\".",
    pages: ["/academics/minors"],
    component: "MinorsPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-certificates-link-generic-001",
    rule: "link-generic",
    title: "Catalog addendum link says \"Click here\"",
    description: "The link to the catalog addendum PDF reads \"Click here\".",
    fixDescription: "Link text names the document and its file type and size.",
    pages: ["/academics/certificates"],
    component: "CertificatesPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-calendar-caption-001",
    rule: "table-no-caption",
    title: "Calendar tables have no captions",
    description: "The Fall and Spring calendar tables have no <caption>.",
    fixDescription: "Adds a caption to each table.",
    pages: ["/academics/calendar"],
    component: "CalendarPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-calendar-headers-001",
    rule: "table-header-association",
    title: "Calendar cells point to header ids that don't exist",
    description: "Each cell has a headers attribute (\"date\", \"event\") left over from an old template, but the header cells' ids are now \"fall-date\" and so on, so the association is broken.",
    fixDescription: "Points each headers attribute at the matching header id.",
    pages: ["/academics/calendar"],
    component: "CalendarPage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-calendar-closed-color-001",
    rule: "color-only-info",
    title: "Campus closures are shown only in red",
    description: "Holidays when campus is closed are shown in red, explained by a legend, with no text in the row saying so.",
    fixDescription: "Adds \"(campus closed)\" to those rows.",
    pages: ["/academics/calendar"],
    component: "CalendarPage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-calendar-pdf-link-001",
    rule: "link-document",
    title: "Printable calendar link doesn't say it's a PDF",
    description: "The printable calendar link opens a PDF without saying so or giving its size.",
    fixDescription: "Appends \"(PDF, 2 KB)\".",
    pages: ["/academics/calendar"],
    component: "CalendarPage",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- /academics/catalog (tier T): "General Catalog 2025-2026", one of the six terrible pages (plan 07) ----------
  // A PDF-era course catalog kept as an HTML page and never modernized. CSS: styles/features/catalog.css.
  {
    id: "academics-catalog-subject-menu-list-001",
    rule: "list-structure",
    title: "\"Jump to subject\" items sit in a <div>, not a list",
    description: "The subject jump menu's items are <li> elements inside a <div>, so they aren't announced as a list.",
    fixDescription: "Wraps the items in a <ul>.",
    pages: ["/academics/catalog"],
    component: "SubjectMenu",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-catalog-subject-menu-hover-001",
    rule: "kbd-hover-only-menu",
    title: "Subject menu only opens on hover",
    description: "\"Jump to subject\" is plain text that reveals the subject list only on mouse hover; there is no way to open it with a keyboard.",
    fixDescription: "Becomes a button with aria-expanded that opens and closes the list.",
    pages: ["/academics/catalog"],
    component: "SubjectMenu",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "academics-catalog-subject-menu-event-001",
    rule: "event-handler-device",
    title: "Subject list highlight uses onmouseover only",
    description: "Subject list items highlight through inline onmouseover/onmouseout handlers; keyboard focus gets nothing.",
    fixDescription: "Removes the handlers; CSS :hover and :focus highlight the item.",
    pages: ["/academics/catalog"],
    component: "SubjectMenu",
    mechanism: "behavior",
    severity: "minor",
  },
  {
    id: "academics-catalog-subject-menu-aria-001",
    rule: "aria-required-parent",
    title: "Subject list items use role=\"option\" outside a listbox",
    description: "A never-finished combobox attempt left role=\"option\" and aria-selected on the subject links, but the list has no role=\"listbox\" or role=\"combobox\" parent.",
    fixDescription: "Removes the leftover roles; it's a plain navigation list.",
    pages: ["/academics/catalog"],
    component: "SubjectMenu",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-catalog-subject-icon-alt-001",
    rule: "alt-suspicious",
    title: "Subject icon alt text is a file name",
    description: "The small icon before each subject heading has alt=\"subj.gif\", left over from the image's file name.",
    fixDescription: "Marks the icon decorative (alt=\"\") since the heading text already names the subject.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-subject-icon-title-001",
    rule: "img-title-attr",
    title: "Subject icon repeats its alt text in a title attribute",
    description: "The subject icon also carries a title identical to its old alt text, so screen readers would announce it twice.",
    fixDescription: "Removes the title attribute.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-intro-justified-001",
    rule: "text-justified",
    title: "Catalog introduction is fully justified",
    description: "The catalog's introduction paragraph uses text-align: justify, creating uneven word spacing.",
    fixDescription: "Left-aligns the paragraph.",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "academics-catalog-table-caption-001",
    rule: "table-no-caption",
    title: "Subject course tables have no caption",
    description: "None of the 16 per-subject course tables have a <caption>.",
    fixDescription: "Each table gets a caption naming its subject.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-table-headers-001",
    rule: "table-header-association",
    title: "Course table cells point at header ids that don't exist",
    description: "Cells use headers=\"code\", \"title\" and so on, but the header cells' ids are \"col-code\", \"col-title\" — left over from copying one subject's table to build the rest.",
    fixDescription: "headers attributes match the <th> ids.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-catalog-desc-small-001",
    rule: "text-small",
    title: "Course descriptions are 10px",
    description: "Every course description in the catalog is set at 10px.",
    fixDescription: "Uses the site's body text size.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "academics-catalog-desc-contrast-001",
    rule: "contrast-text-low",
    title: "Course descriptions are light gray",
    description: "Course description text is #aaaaaa on white, about 2.3:1.",
    fixDescription: "Uses #767676, just above the 4.5:1 minimum.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "academics-catalog-reflow-001",
    rule: "reflow-horizontal-scroll",
    title: "Catalog content forces horizontal page scrolling",
    description: "The catalog body has a fixed 62rem width, so the whole page scrolls sideways on narrow screens and at 200% zoom.",
    fixDescription: "Uses a fluid width with its own scroll container for wide tables only.",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "academics-catalog-focus-outline-001",
    rule: "focus-indicator-missing",
    title: "Catalog links hide the focus outline",
    description: "The catalog stylesheet sets outline: none on links, so keyboard focus is invisible.",
    fixDescription: "Restores a visible focus outline.",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "academics-catalog-view-link-001",
    rule: "link-generic",
    title: "Every course has a \"View\" link",
    description: "Each of the catalog's 300-plus course rows ends with a link reading only \"View\".",
    fixDescription: "The link names the course.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-catalog-download-pdf-001",
    rule: "link-document",
    title: "\"Download the catalog\" link doesn't say it's a PDF",
    description: "The full catalog download opens a PDF with no file type or size.",
    fixDescription: "Adds \"(PDF, 2 KB)\".",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-print-window-001",
    rule: "link-new-window",
    title: "\"Print-friendly version\" opens a new tab without warning",
    description: "The print-friendly link opens in a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\".",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-back-to-top-001",
    rule: "link-empty",
    title: "\"Back to top\" links have no accessible name",
    description: "Each subject section ends with an icon-only \"back to top\" link with no text.",
    fixDescription: "Adds visually hidden text \"Back to top\".",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-catalog-jump-select-001",
    rule: "select-missing-label",
    title: "\"Jump to subject\" select has no label",
    description: "The subject-jump <select> has no associated label.",
    fixDescription: "Adds a visible <label>.",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "academics-catalog-impacted-color-001",
    rule: "color-only-info",
    title: "Impacted-enrollment subjects are marked only by a colored dot",
    description: "Computer Science and Nursing show a small red dot next to the subject heading, with no text explaining it.",
    fixDescription: "Adds the visible text \"(impacted enrollment)\".",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-catalog-table-border-001",
    rule: "contrast-ui-low",
    title: "Course table borders are barely visible",
    description: "Table row borders are #eeeeee on white, about 1.2:1.",
    fixDescription: "Uses #8f8f8f, just above the 3:1 minimum for UI components.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "css",
    severity: "moderate",
  },
  {
    id: "academics-catalog-desc-clip-001",
    rule: "reflow-clipped-text",
    title: "Course descriptions are clipped at a fixed height",
    description: "Each description is a fixed 2.4rem tall with overflow hidden, so enlarged text is cut off mid-sentence.",
    fixDescription: "Lets the description grow with its content.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "css",
    severity: "moderate",
  },
  {
    id: "academics-catalog-heading-skip-001",
    rule: "heading-skipped",
    title: "Subject headings jump from h1 straight to h4",
    description: "Each subject heading (\"Computer Science\") is an <h4> with nothing between it and the page's <h1>.",
    fixDescription: "Subject headings become <h2>.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-catalog-heading-possible-001",
    rule: "heading-possible",
    title: "\"Lower Division\" and \"Upper Division\" are bold paragraphs",
    description: "The course-level group labels within each subject look like headings but are bold paragraphs.",
    fixDescription: "Makes them <h3> headings.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-catalog-tabs-level-001",
    rule: "kbd-tabs-wrong-keys",
    title: "\"Undergraduate / Graduate\" tabs don't support arrow keys",
    description: "The two level tabs have the right roles, but arrow keys, Home and End do nothing, and only the active tab is in the tab order.",
    fixDescription: "Arrow keys, Home and End move between tabs (WAI-ARIA APG pattern).",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "academics-catalog-accordion-notes-001",
    rule: "sr-accordion-state",
    title: "\"General Education\" notes don't announce open or closed",
    description: "The General Education requirement notes expand and collapse, but the trigger has no aria-expanded or aria-controls.",
    fixDescription: "Adds aria-expanded and aria-controls to the trigger.",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "academics-catalog-index-table-001",
    rule: "table-layout",
    title: "Subject index box is built with a layout table",
    description: "The small \"Subjects in this catalog\" box lines up two columns of subject codes with a borderless <table>, not CSS.",
    fixDescription: "Uses a two-column CSS grid of <div>s.",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-catalog-underline-001",
    rule: "underline-non-link",
    title: "\"revised annually\" is underlined, not a link",
    description: "\"This catalog is revised annually\" underlines \"revised annually\" for emphasis, so it looks like a link.",
    fixDescription: "Uses bold instead of an underline.",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-orphan-label-001",
    rule: "label-orphaned",
    title: "A leftover <label> points at nothing",
    description: "A <label>Catalog year</label> from a retired year-picker was never removed and has no for attribute or nearby control.",
    fixDescription: "Removes the leftover label.",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-dup-id-001",
    rule: "duplicate-id",
    title: "Two subjects' \"Notes\" paragraphs share the same id",
    description: "The Art and Music subject sections were both built from the same template and both kept id=\"subject-notes\" on their notes paragraph.",
    fixDescription: "Each notes paragraph gets its own id.",
    pages: ["/academics/catalog"],
    component: "CatalogSubject",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-catalog-pdf-icon-alt-001",
    rule: "img-missing-alt",
    title: "PDF icon before the download link has no alt",
    description: "A small PDF icon sits before the \"Download the catalog\" link with no alt attribute.",
    fixDescription: "Marks the icon decorative (alt=\"\") since the link text already says \"Download\".",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-print-icon-alt-001",
    rule: "alt-redundant",
    title: "Print icon's alt text duplicates the link beside it",
    description: "The small printer icon before \"Print-friendly version\" has alt=\"Print-friendly version\", the same as the link text right next to it.",
    fixDescription: "Marks the icon decorative (alt=\"\").",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-catalog-quick-filter-001",
    rule: "fieldset-missing",
    title: "\"4 credits\" and \"No prerequisites\" checkboxes are not grouped",
    description: "The two quick-filter checkboxes sit loose with no fieldset or shared question.",
    fixDescription: "Wraps them in a fieldset with the legend \"Quick filters\".",
    pages: ["/academics/catalog"],
    component: "CatalogPage",
    mechanism: "markup",
    severity: "moderate",
  },
];
