import { colleges, departments } from "../../data/catalog";
import type { ScenarioDef } from "./types";

const college = (slug: string) => `/academics/colleges/${slug}`;
/** Colleges with at least one catalog department get the department list and jump menu. */
const collegesWithDepartments = colleges.filter((c) => departments.some((d) => d.college === c.slug)).map((c) => college(c.slug));

/** Every page built on the academics CMS templates (the catalog and course search are plans 06/07). */
export const cmsPages = [
  "/academics", "/academics/colleges/:slug", "/academics/departments/:slug", "/academics/programs",
  "/academics/programs/:slug", "/academics/minors", "/academics/certificates", "/academics/calendar",
  "/faculty", "/faculty/:slug",
];

export const academicsScenarios: ScenarioDef[] = [
  // ---------- Section template (every academics CMS page) ----------
  {
    id: "academics-sidebar-contrast-001",
    rule: "contrast-text-low",
    title: "Academics sidebar links have low contrast",
    description: "The CMS theme colors the sidebar navigation links slate gray (#8c9aa3) on the beige sidebar (#f3f1ea), about 2.6:1.",
    fixDescription: "Uses the section link color (#1f4f7a, about 7.6:1).",
    pages: cmsPages,
    component: "CmsPage / section sidebar",
    mechanism: "css",
    severity: "serious",
  },

  // ---------- /academics ----------
  {
    id: "academics-hub-card-alt-redundant-001",
    rule: "alt-redundant",
    title: "College card photos repeat the card title",
    description: "Each college card photo has alt text identical to the card title next to it (\"College of Science\"), so screen readers read the name twice.",
    fixDescription: "Marks the photos decorative (alt=\"\") because the title already names the card.",
    pages: ["/academics"],
    component: "AcademicsHub / Card",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- CollegeLanding (/academics/colleges/:slug) ----------
  {
    id: "academics-college-hero-alt-suspicious-001",
    rule: "alt-suspicious",
    title: "College banner photo uses its file name as alt text",
    description: "The banner photo's alt text is the uploaded file name (for example \"college-engineering_banner_v2.jpg\").",
    fixDescription: "Uses alt text that describes the photo.",
    pages: ["/academics/colleges/:slug"],
    component: "CollegeLanding / Hero",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-college-fake-heading-001",
    rule: "heading-possible",
    title: "\"Why study at…\" is a bold paragraph, not a heading",
    description: "The highlights section is introduced by bold paragraph text styled like a heading, so it is missing from the heading outline.",
    fixDescription: "Uses an <h2>.",
    pages: ["/academics/colleges/:slug"],
    component: "CollegeLanding",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-college-dept-link-generic-001",
    rule: "link-generic",
    title: "Department links all say \"Learn more\"",
    description: "Each department summary ends with a \"Learn more\" link, which is meaningless out of context (for example in a screen reader's links list).",
    fixDescription: "Link text names the department: \"Visit the Department of Biology\".",
    pages: collegesWithDepartments,
    component: "CollegeLanding / department list",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-college-jump-select-label-001",
    rule: "select-missing-label",
    title: "\"Jump to\" menu has no label",
    description: "The quick-jump <select> for departments and programs has only a \"-- Select --\" first option and no label.",
    fixDescription: "Adds a visible <label> associated with the select.",
    pages: collegesWithDepartments,
    component: "CollegeLanding / JumpMenu",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "academics-college-video-title-001",
    rule: "iframe-missing-title",
    title: "College video embed has no title",
    description: "The embedded video player's <iframe> has no title attribute, so screen readers announce only \"frame\".",
    fixDescription: "Gives the iframe a title matching the video.",
    // Colleges with a video (collegeVideos in pages/academics/colleges/$slug.tsx).
    pages: [college("engineering"), college("science"), college("health-sciences")],
    component: "CollegeLanding / VideoEmbed",
    mechanism: "markup",
    severity: "serious",
  },

  // ---------- DepartmentPage (/academics/departments/:slug) ----------
  {
    id: "academics-dept-heading-skip-001",
    rule: "heading-skipped",
    title: "Department template jumps from h2 to h4",
    description: "Under \"Academics\" (h2), the Degree Programs and Courses headings are <h4>, skipping h3. The old CMS template hard-codes the smaller heading style.",
    fixDescription: "Uses <h3> for the subsections.",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-dept-photo-alt-001",
    rule: "img-missing-alt",
    title: "Department photo has no alt attribute",
    description: "The photo floated beside the department overview was uploaded without alt text; the img has no alt attribute at all.",
    fixDescription: "Adds alt text describing the photo.",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "academics-dept-course-table-caption-001",
    rule: "table-no-caption",
    title: "Course list table has no caption",
    description: "The department course table is introduced only by a nearby heading; it has no <caption> naming it.",
    fixDescription: "Adds a caption (\"Computer Science courses, 2026–27\").",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage / course table",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-dept-full-color-001",
    rule: "color-only-info",
    title: "Full courses are shown only in red",
    description: "Courses whose Fall 2026 sections are all full are marked only by red text, explained by a legend (\"Courses in red are full\").",
    fixDescription: "Adds a visible \"Full\" label to those courses.",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage / course table",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-dept-document-link-001",
    rule: "link-document",
    title: "PDF links don't say they are PDFs",
    description: "The Documents & Forms links open PDF files but don't mention the file type or size.",
    fixDescription: "Appends \"(PDF, 2 KB)\" to each link.",
    pages: ["/academics/departments/:slug"],
    component: "DepartmentPage / documents",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- /academics/programs ----------
  {
    id: "academics-programs-college-select-001",
    rule: "select-missing-label",
    title: "College filter has no label",
    description: "The college filter <select> sits next to plain \"College:\" text that is not a <label>.",
    fixDescription: "Turns the text into a <label> for the select.",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "academics-programs-level-fieldset-001",
    rule: "fieldset-missing",
    title: "Degree level radios are not grouped",
    description: "The All / Undergraduate / Graduate radio buttons have no fieldset or legend, so \"Degree level\" is not announced with them.",
    fixDescription: "Wraps the radios in a fieldset with a \"Degree level\" legend.",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-programs-reset-javascript-001",
    rule: "link-javascript",
    title: "\"Reset filters\" is an href=\"#\" link",
    description: "Reset filters is a link to \"#\" with a click handler: it acts as a button but is announced as a link that goes nowhere.",
    fixDescription: "Uses a <button>.",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-programs-count-status-001",
    rule: "sr-status-not-announced",
    title: "Result count changes silently",
    description: "When a filter changes, the \"Showing N programs\" text updates, but it is not a live region, so screen reader users aren't told.",
    fixDescription: "Makes the count a polite status region (role=\"status\").",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "behavior",
    severity: "moderate",
  },
  {
    id: "academics-programs-impacted-color-001",
    rule: "color-only-info",
    title: "Impacted programs are marked by a red dot only",
    description: "Impacted programs have a small red dot next to the name and a legend at the top; the dot has no text alternative.",
    fixDescription: "Replaces the dot with a visible \"Impacted\" label.",
    pages: ["/academics/programs"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "serious",
  },

  // ---------- ProgramPage (/academics/programs/:slug) ----------
  {
    id: "academics-program-req-table-caption-001",
    rule: "table-no-caption",
    title: "Degree requirements table has no caption",
    description: "The unit requirements table has no <caption>.",
    fixDescription: "Adds a caption naming the degree.",
    pages: ["/academics/programs/:slug"],
    component: "ProgramPage",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- Minors, certificates, calendar ----------
  {
    id: "academics-minors-link-generic-001",
    rule: "link-generic",
    title: "Change of major/minor form link says \"here\"",
    description: "The link to the Change of Major/Minor form reads just \"here\".",
    fixDescription: "Link text names where the form is: \"from the Office of the Registrar\".",
    pages: ["/academics/minors"],
    component: "MinorsPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-certificates-link-generic-001",
    rule: "link-generic",
    title: "Catalog addendum link says \"Click here\"",
    description: "The link to the catalog addendum PDF reads \"Click here\".",
    fixDescription: "Link text names the document and its file type and size.",
    pages: ["/academics/certificates"],
    component: "CertificatesPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "academics-calendar-caption-001",
    rule: "table-no-caption",
    title: "Calendar tables have no captions",
    description: "The Fall and Spring calendar tables have no <caption>.",
    fixDescription: "Adds a caption to each table.",
    pages: ["/academics/calendar"],
    component: "CalendarPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "academics-calendar-headers-001",
    rule: "table-header-association",
    title: "Calendar cells point to header ids that don't exist",
    description: "Each cell has a headers attribute (\"date\", \"event\") left over from an old template, but the header cells' ids are now \"fall-date\" and so on, so the association is broken.",
    fixDescription: "Points each headers attribute at the matching header id.",
    pages: ["/academics/calendar"],
    component: "CalendarPage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-calendar-closed-color-001",
    rule: "color-only-info",
    title: "Campus closures are shown only in red",
    description: "Holidays when campus is closed are shown in red, explained by a legend, with no text in the row saying so.",
    fixDescription: "Adds \"(campus closed)\" to those rows.",
    pages: ["/academics/calendar"],
    component: "CalendarPage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "academics-calendar-pdf-link-001",
    rule: "link-document",
    title: "Printable calendar link doesn't say it's a PDF",
    description: "The printable calendar link opens a PDF without saying so or giving its size.",
    fixDescription: "Appends \"(PDF, 2 KB)\".",
    pages: ["/academics/calendar"],
    component: "CalendarPage",
    mechanism: "markup",
    severity: "minor",
  },
];
