import type { ScenarioDef } from "./types";

const TEAM_PAGES = ["mens-basketball", "womens-basketball", "womens-soccer", "baseball", "volleyball", "cross-country"].map((s) => `/athletics/teams/${s}`);

export const athleticsScenarios: ScenarioDef[] = [
  // ---------- /athletics (tier H) ----------
  {
    id: "athletics-home-ticker-color-001",
    rule: "color-only-info",
    title: "Score ticker shows wins and losses by color only",
    description: "Ticker scores are green for a win and red for a loss, with no W or L, so the outcome is lost without color vision.",
    fixDescription: "Adds a visible W, L or T before each score.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-home-ticker-contrast-001",
    rule: "contrast-text-low",
    title: "Ticker dates are dark gray on black",
    description: "The small date and sport line in each ticker item is #5a5a5a on #000 (about 3.0:1).",
    fixDescription: "Uses #767676, just above the 4.5:1 minimum.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "athletics-home-ticker-clip-001",
    rule: "reflow-fixed-dimensions",
    title: "Ticker items have a fixed height and clip text",
    description: "Each ticker item is a fixed 4.5rem tall with overflow hidden, so enlarged text is cut off.",
    fixDescription: "Lets the items grow with their content.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "css",
    severity: "moderate",
  },
  {
    id: "athletics-home-ticker-motion-001",
    rule: "motion-animated-announcement",
    title: "Score ticker scrolls with no way to stop it",
    description: "The score ticker scrolls sideways forever, with no pause control, and keeps moving on hover and while a score link has focus, so scores slide away mid-read.",
    fixDescription: "Adds a Pause button and stops the ticker on hover and focus.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "behavior",
    severity: "moderate",
  },
  {
    id: "athletics-home-ticker-reduced-motion-001",
    rule: "motion-ignores-reduced-motion",
    title: "Score ticker ignores reduced motion",
    description: "The ticker keeps scrolling when the visitor has asked for reduced motion.",
    fixDescription: "Under prefers-reduced-motion the ticker is a static, swipeable strip.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "athletics-home-focus-001",
    rule: "focus-indicator-missing",
    title: "Ticker and team tile links hide the focus outline",
    description: "The vendor theme sets outline: none on ticker and team tile links, so keyboard focus is invisible.",
    fixDescription: "Restores a visible gold focus outline.",
    pages: ["/athletics"],
    component: "AthleticsHome",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "athletics-home-headline-alt-001",
    rule: "img-missing-alt",
    title: "Headline photos have no alt attribute",
    description: "The photos in the Owls headlines have no alt attribute.",
    fixDescription: "Adds alt text describing each photo.",
    pages: ["/athletics"],
    component: "AthleticsHeadlines",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "athletics-home-readmore-001",
    rule: "link-generic",
    title: "Headlines end in \"Read more\" links",
    description: "Every headline ends with an identical \"Read more »\" link that says nothing about the story.",
    fixDescription: "The link text names the story.",
    pages: ["/athletics"],
    component: "AthleticsHeadlines",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-home-heading-skip-001",
    rule: "heading-skipped",
    title: "Headline titles skip from h2 to h4",
    description: "Headline titles are <h4> directly under the \"Owls Headlines\" <h2>.",
    fixDescription: "Headline titles become <h3>.",
    pages: ["/athletics"],
    component: "AthleticsHeadlines",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-home-social-empty-001",
    rule: "link-empty",
    title: "Social icon links have no text",
    description: "The \"Follow the Owls\" links contain only icons, so they have no accessible name.",
    fixDescription: "Adds visually hidden text naming each network.",
    pages: ["/athletics"],
    component: "AthleticsSocial",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-home-tickets-window-001",
    rule: "link-new-window",
    title: "Ticket link opens a new tab without warning",
    description: "\"Buy tickets\" opens the ticket office page in a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\" to the link.",
    pages: ["/athletics"],
    component: "AthleticsHome",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-home-games-caption-001",
    rule: "table-no-caption",
    title: "Upcoming home games table has no caption",
    description: "The upcoming home games table has no <caption>, so it is announced without a name.",
    fixDescription: "Adds a caption.",
    pages: ["/athletics"],
    component: "UpcomingGames",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-home-underline-001",
    rule: "underline-non-link",
    title: "Underlined text that is not a link",
    description: "\"Students get in free\" is underlined for emphasis, so it looks like a link.",
    fixDescription: "Uses bold instead of an underline.",
    pages: ["/athletics"],
    component: "AthleticsHome",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- /athletics/teams (tier M) ----------
  {
    id: "athletics-teams-season-heading-001",
    rule: "heading-possible",
    title: "Season group labels are bold paragraphs",
    description: "\"Fall Sports\", \"Winter Sports\" and \"Spring Sports\" look like headings but are bold paragraphs.",
    fixDescription: "Makes them <h2> headings.",
    pages: ["/athletics/teams"],
    component: "TeamsIndex",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-teams-link-redundant-001",
    rule: "link-redundant",
    title: "Team photo and name link separately to the same page",
    description: "Each tile's photo and name are two separate links to the same team page, doubling tab stops.",
    fixDescription: "The photo is no longer a link and is marked decorative.",
    pages: ["/athletics/teams"],
    component: "TeamTile",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-teams-link-duplicate-001",
    rule: "link-nearby-duplicate",
    title: "Every tile has identical \"Roster\" and \"Schedule\" links",
    description: "Six \"Roster\" and six \"Schedule\" links point to different teams, so a links list is ambiguous.",
    fixDescription: "Adds the team name to each link (visually hidden).",
    pages: ["/athletics/teams"],
    component: "TeamTile",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-teams-record-contrast-001",
    rule: "contrast-text-low",
    title: "Team records are gray on dark gray",
    description: "The record and coach line on each tile is #777 on #1e1e1e (about 3.7:1).",
    fixDescription: "Uses #868686, just above the 4.5:1 minimum.",
    pages: ["/athletics/teams"],
    component: "TeamTile",
    mechanism: "css",
    severity: "serious",
  },

  // ---------- /athletics/scores (tier M) ----------
  {
    id: "athletics-scores-select-label-001",
    rule: "select-missing-label",
    title: "Sport filter has no label",
    description: "The sport filter <select> shows \"All sports\" but has no label.",
    fixDescription: "Adds a visible <label>.",
    pages: ["/athletics/scores"],
    component: "ScoresPage",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "athletics-scores-caption-001",
    rule: "table-no-caption",
    title: "Results table has no caption",
    description: "The results table has no <caption>.",
    fixDescription: "Adds a caption that also reflects the sport filter.",
    pages: ["/athletics/scores"],
    component: "ScoresPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-scores-details-generic-001",
    rule: "link-generic",
    title: "Every result has a \"Details\" link",
    description: "Each row ends with a link reading only \"Details\".",
    fixDescription: "The link names the game.",
    pages: ["/athletics/scores"],
    component: "ScoresPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-scores-reflow-001",
    rule: "reflow-horizontal-scroll",
    title: "Results table forces horizontal page scrolling",
    description: "The table has a 52rem minimum width and no scroll container, so the whole page scrolls sideways on narrow screens and at 400% zoom.",
    fixDescription: "Wraps the table in its own scroll container and drops the minimum width.",
    pages: ["/athletics/scores"],
    component: "ScoresPage",
    mechanism: "css",
    severity: "serious",
  },

  // ---------- /athletics/teams/:slug (TeamPage, tier M) ----------
  {
    id: "athletics-team-roster-headers-001",
    rule: "table-header-association",
    title: "Roster cells point to the wrong headers",
    description: "Roster cells use hard-coded headers attributes that are off by one column (the last points at a header that doesn't exist), so screen readers announce the wrong column.",
    fixDescription: "Removes the headers attributes and uses scope on the header cells.",
    pages: ["/athletics/teams/:slug"],
    component: "TeamPage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-team-schedule-caption-001",
    rule: "table-no-caption",
    title: "Team schedule table has no caption",
    description: "The schedule and results table has no <caption>.",
    fixDescription: "Adds a caption with the team and season.",
    pages: ["/athletics/teams/:slug"],
    component: "TeamPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-team-conference-color-001",
    rule: "color-only-info",
    title: "Conference games are marked only by a gold stripe",
    description: "Conference games get a gold left border and nothing else, so the distinction is visual and color only.",
    fixDescription: "Adds a visible \"Conference\" label to those rows.",
    pages: ["/athletics/teams/:slug"],
    component: "TeamPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-team-stats-small-001",
    rule: "text-small",
    title: "Team stat labels are 10px",
    description: "The labels in the team stats band are 10px uppercase text.",
    fixDescription: "Uses 0.95rem labels.",
    pages: ["/athletics/teams/:slug"],
    component: "TeamPage",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "athletics-team-video-title-001",
    rule: "iframe-missing-title",
    title: "Highlights video frame has no title",
    description: "The season highlights embed is an <iframe> with no title.",
    fixDescription: "Adds a title naming the video.",
    pages: TEAM_PAGES.filter((p) => !p.includes("basketball")),
    component: "VideoEmbed",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-team-schedule-pdf-001",
    rule: "link-document",
    title: "Printable schedule link doesn't say it's a PDF",
    description: "\"Printable schedule\" downloads a PDF with no file type or size.",
    fixDescription: "Adds the file type and size.",
    pages: ["/athletics/teams/mens-basketball"],
    component: "TeamPage",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- /athletics/athletes/:slug (tier L) ----------
  {
    id: "athletics-athlete-photo-alt-001",
    rule: "alt-suspicious",
    title: "Athlete photo alt text is just \"photo\"",
    description: "Every athlete headshot has alt=\"photo\", which says nothing about the image.",
    fixDescription: "Uses alt text describing the athlete's photo.",
    pages: ["/athletics/athletes/:slug"],
    component: "AthleteProfile",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- /athletics/schedule (tier T): "Composite Schedule", one of the six terrible pages (plan 07) ----------
  // A third-party sports-scheduling widget dropped into the section. CSS: styles/features/athletics-schedule.css.
  {
    id: "athletics-schedule-carousel-pause-001",
    rule: "motion-autorotate-no-pause",
    title: "Featured matchups carousel rotates with no pause",
    description: "The \"Featured matchups\" strip advances every 6 seconds forever, with no pause control, and ignores prefers-reduced-motion.",
    fixDescription: "Adds a Pause/Play button and stops auto-rotating under reduced motion.",
    pages: ["/athletics/schedule"],
    component: "FeaturedMatchups",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "athletics-schedule-carousel-kbd-001",
    rule: "kbd-carousel-unreachable",
    title: "Carousel dots can't be reached by keyboard",
    description: "The featured-matchup dots are <span> elements with click handlers, so keyboard users can't jump between slides.",
    fixDescription: "The dots become named <button>s (\"Slide 2 of 4\"), with the current one marked aria-current.",
    pages: ["/athletics/schedule"],
    component: "FeaturedMatchups",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "athletics-schedule-matchup-redundant-001",
    rule: "link-redundant",
    title: "Each featured matchup has two links to the same ticket page",
    description: "A slide's photo link and its separate \"Buy tickets\" link both go to the same ticket page, doubling the tab stops.",
    fixDescription: "The photo is no longer a link and is marked decorative; only \"Buy tickets\" links.",
    pages: ["/athletics/schedule"],
    component: "FeaturedMatchups",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-tabs-view-001",
    rule: "kbd-tabs-wrong-keys",
    title: "\"Upcoming / Results\" tabs don't support arrow keys",
    description: "The two view tabs have the right roles, but arrow keys, Home and End do nothing, and only the active tab is in the tab order.",
    fixDescription: "Arrow keys, Home and End move between tabs (WAI-ARIA APG pattern).",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "athletics-schedule-sport-label-001",
    rule: "select-missing-label",
    title: "Sport filter has no label",
    description: "The sport filter <select> shows \"All sports\" but has no label.",
    fixDescription: "Adds a visible <label>.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "athletics-schedule-quick-filters-001",
    rule: "fieldset-missing",
    title: "\"Home games\" and \"Conference games\" checkboxes are not grouped",
    description: "The two quick-filter checkboxes sit loose with no fieldset or shared question.",
    fixDescription: "Wraps them in a fieldset with the legend \"Quick filters\".",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-legend-list-001",
    rule: "list-structure",
    title: "Icon legend items sit in a <div>, not a list",
    description: "The Tickets / TV / Result legend is five <span> items in a <div>, so it isn't announced as a list.",
    fixDescription: "Wraps the items in a <ul>.",
    pages: ["/athletics/schedule"],
    component: "ScheduleLegend",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-legend-table-001",
    rule: "table-layout",
    title: "Leftover \"Key\" box is built with a layout table",
    description: "A leftover \"Key\" box repeating the legend lines up its icons and text with a borderless <table>, not CSS.",
    fixDescription: "Uses a flex row of <div>s.",
    pages: ["/athletics/schedule"],
    component: "ScheduleLegend",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-legend-clip-001",
    rule: "reflow-fixed-dimensions",
    title: "Legend row has a fixed height and clips at large text sizes",
    description: "The legend is a fixed 2.5rem tall with overflow hidden, so enlarged text is cut off.",
    fixDescription: "Lets the legend grow with its content.",
    pages: ["/athletics/schedule"],
    component: "ScheduleLegend",
    mechanism: "css",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-legend-underline-001",
    rule: "underline-non-link",
    title: "\"Conference game\" note is underlined, not a link",
    description: "The \"* = conference game\" note is underlined for emphasis, so it looks like a link.",
    fixDescription: "Uses bold instead of an underline.",
    pages: ["/athletics/schedule"],
    component: "ScheduleLegend",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-month-heading-001",
    rule: "heading-skipped",
    title: "Month headings jump from h1 straight to h4",
    description: "Each month's group heading (\"November 2026\") is an <h4> with nothing between it and the page's <h1>.",
    fixDescription: "Month headings become <h2>.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-current-month-001",
    rule: "aria-invalid-value",
    title: "Current month badge uses aria-current=\"yes\"",
    description: "The \"You are here\" badge on the current month sets aria-current=\"yes\", which is not a valid token.",
    fixDescription: "Uses aria-current=\"date\".",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-table-caption-001",
    rule: "table-no-caption",
    title: "Month tables have no caption",
    description: "None of the month schedule tables have a <caption>.",
    fixDescription: "Each table gets a caption naming its month.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-table-headers-001",
    rule: "table-header-association",
    title: "Table cells point at header ids that don't exist",
    description: "Cells use headers=\"date\", \"sport\", and so on, but the header cells' ids are \"col-date\", \"col-sport\".",
    fixDescription: "headers attributes match the <th> ids.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-schedule-ticket-empty-001",
    rule: "link-empty",
    title: "Ticket icon link has no accessible name",
    description: "The ticket icon next to home games is a link containing only an icon, so it has no name.",
    fixDescription: "Adds visually hidden text naming the opponent and date.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-schedule-tv-badge-001",
    rule: "img-empty-alt-meaningful",
    title: "TV badge has alt=\"\" but carries information",
    description: "The small TV icon marking nationally televised games has alt=\"\", so the fact is lost without sight.",
    fixDescription: "Gives the icon alt=\"Nationally televised\".",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-schedule-tv-badge-title-001",
    rule: "img-title-attr",
    title: "TV badge repeats its alt text in a title attribute",
    description: "Once labeled, the TV icon also carries a title identical to its alt text, so screen readers announce it twice.",
    fixDescription: "Removes the title attribute.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-result-color-001",
    rule: "color-only-info",
    title: "Win or loss is shown by color only",
    description: "Completed games show the score in green (win) or red (loss) text with no W, L or T letter.",
    fixDescription: "Adds a visible W, L or T before the score.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-schedule-details-generic-001",
    rule: "link-generic",
    title: "Every row has a \"Details\" link",
    description: "Each row ends with a link reading only \"Details\".",
    fixDescription: "The link names the matchup.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-conf-note-id-001",
    rule: "duplicate-id",
    title: "Two months' conference notes share the same id",
    description: "The \"* Conference game\" note under November and the one under December were copied from the same template and both kept id=\"conf-note\".",
    fixDescription: "Each note gets its own id.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-sticky-focus-001",
    rule: "focus-indicator-missing",
    title: "Sticky table header covers the focused row",
    description: "Each month table's header row is sticky with a solid background and sits above the content, so tabbing to a row link near the top of the table hides it under the header.",
    fixDescription: "Removes the sticky positioning, so the header scrolls normally and never overlaps a focused row.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "athletics-schedule-row-contrast-001",
    rule: "contrast-ui-low",
    title: "Row dividers are barely visible",
    description: "Table row borders are #eeeeee on white, about 1.2:1, so rows run together for low-vision readers.",
    fixDescription: "Uses #8f8f8f, just above the 3:1 minimum for UI components.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "css",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-fine-print-small-001",
    rule: "text-small",
    title: "\"All times Pacific\" note is 10px",
    description: "The time-zone note under each table is set at 10px.",
    fixDescription: "Uses the site's body text size.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-fine-print-contrast-001",
    rule: "contrast-text-low",
    title: "\"All times Pacific\" note is light gray",
    description: "The time-zone note is #4f4f4f on this section's #121212 background, about 2.3:1 (this scenario predates the sports section's dark theme; the color was never rechecked against it).",
    fixDescription: "Uses #7f7f7f, just above the 4.5:1 minimum.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-schedule-pdf-001",
    rule: "link-document",
    title: "\"Printable schedule\" link doesn't say it's a PDF",
    description: "The printable composite schedule downloads a PDF with no file type or size.",
    fixDescription: "Adds \"(PDF, 2 KB)\".",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-print-icon-alt-001",
    rule: "img-missing-alt",
    title: "Printer icon before the PDF link has no alt",
    description: "A small printer icon sits before the \"Printable schedule\" link with no alt attribute.",
    fixDescription: "Marks the icon decorative (alt=\"\") since the link text already says \"Printable\".",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-tickets-window-001",
    rule: "link-new-window",
    title: "\"Ticket office\" link opens a new tab without warning",
    description: "The season ticket office link opens in a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\".",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-venue-title-001",
    rule: "title-redundant",
    title: "Venue links repeat their text as a title",
    description: "Each venue link has a title attribute identical to its link text.",
    fixDescription: "Removes the title attribute.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-schedule-checkbox-tabindex-001",
    rule: "focus-positive-tabindex",
    title: "Quick-filter checkboxes carry leftover positive tabindex",
    description: "The \"Home games\" and \"Conference games\" checkboxes have tabindex=\"5\" and \"6\" from an older layout, so Tab can visit them out of order.",
    fixDescription: "Removes the tabindex values; order follows the page.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-schedule-orphan-label-001",
    rule: "label-orphaned",
    title: "A leftover <label> points at nothing",
    description: "A <label>Division</label> from a retired division filter was never removed and has no for attribute or nearby control.",
    fixDescription: "Removes the leftover label.",
    pages: ["/athletics/schedule"],
    component: "SchedulePage",
    mechanism: "markup",
    severity: "minor",
  },
];
