import type { ScenarioDef } from "./types";

const TEAM_PAGES = ["mens-basketball", "womens-basketball", "womens-soccer", "baseball", "volleyball", "cross-country"].map((s) => `/athletics/teams/${s}`);

export const athleticsScenarios: ScenarioDef[] = [
  // ---------- /athletics (tier H) ----------
  {
    id: "athletics-home-ticker-color-001",
    rule: "color-only-info",
    title: "Score ticker shows wins and losses by color only",
    description: "Ticker scores are green for a win and red for a loss, with no W or L, so the outcome is lost without color vision.",
    fixDescription: "Adds a visible W, L or T before each score.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-home-ticker-contrast-001",
    rule: "contrast-text-low",
    title: "Ticker dates are dark gray on black",
    description: "The small date and sport line in each ticker item is #5a5a5a on #000 (about 3.0:1).",
    fixDescription: "Uses #b9b9b9 (about 11:1).",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "athletics-home-ticker-clip-001",
    rule: "reflow-fixed-dimensions",
    title: "Ticker items have a fixed height and clip text",
    description: "Each ticker item is a fixed 4.5rem tall with overflow hidden, so enlarged text is cut off.",
    fixDescription: "Lets the items grow with their content.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "css",
    severity: "moderate",
  },
  {
    id: "athletics-home-ticker-motion-001",
    rule: "motion-animated-announcement",
    title: "Score ticker scrolls with no way to stop it",
    description: "The score ticker scrolls sideways forever, with no pause control, and keeps moving on hover and while a score link has focus, so scores slide away mid-read.",
    fixDescription: "Adds a Pause button and stops the ticker on hover and focus.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "behavior",
    severity: "moderate",
  },
  {
    id: "athletics-home-ticker-reduced-motion-001",
    rule: "motion-ignores-reduced-motion",
    title: "Score ticker ignores reduced motion",
    description: "The ticker keeps scrolling when the visitor has asked for reduced motion.",
    fixDescription: "Under prefers-reduced-motion the ticker is a static, swipeable strip.",
    pages: ["/athletics"],
    component: "ScoreTicker",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "athletics-home-focus-001",
    rule: "focus-indicator-missing",
    title: "Ticker and team tile links hide the focus outline",
    description: "The vendor theme sets outline: none on ticker and team tile links, so keyboard focus is invisible.",
    fixDescription: "Restores a visible gold focus outline.",
    pages: ["/athletics"],
    component: "AthleticsHome",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "athletics-home-headline-alt-001",
    rule: "img-missing-alt",
    title: "Headline photos have no alt attribute",
    description: "The photos in the Owls headlines have no alt attribute.",
    fixDescription: "Adds alt text describing each photo.",
    pages: ["/athletics"],
    component: "AthleticsHeadlines",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "athletics-home-readmore-001",
    rule: "link-generic",
    title: "Headlines end in \"Read more\" links",
    description: "Every headline ends with an identical \"Read more »\" link that says nothing about the story.",
    fixDescription: "The link text names the story.",
    pages: ["/athletics"],
    component: "AthleticsHeadlines",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-home-heading-skip-001",
    rule: "heading-skipped",
    title: "Headline titles skip from h2 to h4",
    description: "Headline titles are <h4> directly under the \"Owls Headlines\" <h2>.",
    fixDescription: "Headline titles become <h3>.",
    pages: ["/athletics"],
    component: "AthleticsHeadlines",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-home-social-empty-001",
    rule: "link-empty",
    title: "Social icon links have no text",
    description: "The \"Follow the Owls\" links contain only icons, so they have no accessible name.",
    fixDescription: "Adds visually hidden text naming each network.",
    pages: ["/athletics"],
    component: "AthleticsSocial",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-home-tickets-window-001",
    rule: "link-new-window",
    title: "Ticket link opens a new tab without warning",
    description: "\"Buy tickets\" opens the ticket office page in a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\" to the link.",
    pages: ["/athletics"],
    component: "AthleticsHome",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-home-games-caption-001",
    rule: "table-no-caption",
    title: "Upcoming home games table has no caption",
    description: "The upcoming home games table has no <caption>, so it is announced without a name.",
    fixDescription: "Adds a caption.",
    pages: ["/athletics"],
    component: "UpcomingGames",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-home-underline-001",
    rule: "underline-non-link",
    title: "Underlined text that is not a link",
    description: "\"Students get in free\" is underlined for emphasis, so it looks like a link.",
    fixDescription: "Uses bold instead of an underline.",
    pages: ["/athletics"],
    component: "AthleticsHome",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- /athletics/teams (tier M) ----------
  {
    id: "athletics-teams-season-heading-001",
    rule: "heading-possible",
    title: "Season group labels are bold paragraphs",
    description: "\"Fall Sports\", \"Winter Sports\" and \"Spring Sports\" look like headings but are bold paragraphs.",
    fixDescription: "Makes them <h2> headings.",
    pages: ["/athletics/teams"],
    component: "TeamsIndex",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-teams-link-redundant-001",
    rule: "link-redundant",
    title: "Team photo and name link separately to the same page",
    description: "Each tile's photo and name are two separate links to the same team page, doubling tab stops.",
    fixDescription: "The photo is no longer a link and is marked decorative.",
    pages: ["/athletics/teams"],
    component: "TeamTile",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-teams-link-duplicate-001",
    rule: "link-nearby-duplicate",
    title: "Every tile has identical \"Roster\" and \"Schedule\" links",
    description: "Six \"Roster\" and six \"Schedule\" links point to different teams, so a links list is ambiguous.",
    fixDescription: "Adds the team name to each link (visually hidden).",
    pages: ["/athletics/teams"],
    component: "TeamTile",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-teams-record-contrast-001",
    rule: "contrast-text-low",
    title: "Team records are gray on dark gray",
    description: "The record and coach line on each tile is #777 on #1e1e1e (about 3.7:1).",
    fixDescription: "Uses #b9b9b9 (about 9:1).",
    pages: ["/athletics/teams"],
    component: "TeamTile",
    mechanism: "css",
    severity: "serious",
  },

  // ---------- /athletics/scores (tier M) ----------
  {
    id: "athletics-scores-select-label-001",
    rule: "select-missing-label",
    title: "Sport filter has no label",
    description: "The sport filter <select> shows \"All sports\" but has no label.",
    fixDescription: "Adds a visible <label>.",
    pages: ["/athletics/scores"],
    component: "ScoresPage",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "athletics-scores-caption-001",
    rule: "table-no-caption",
    title: "Results table has no caption",
    description: "The results table has no <caption>.",
    fixDescription: "Adds a caption that also reflects the sport filter.",
    pages: ["/athletics/scores"],
    component: "ScoresPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-scores-details-generic-001",
    rule: "link-generic",
    title: "Every result has a \"Details\" link",
    description: "Each row ends with a link reading only \"Details\".",
    fixDescription: "The link names the game.",
    pages: ["/athletics/scores"],
    component: "ScoresPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-scores-reflow-001",
    rule: "reflow-horizontal-scroll",
    title: "Results table forces horizontal page scrolling",
    description: "The table has a 52rem minimum width and no scroll container, so the whole page scrolls sideways on narrow screens and at 400% zoom.",
    fixDescription: "Wraps the table in its own scroll container and drops the minimum width.",
    pages: ["/athletics/scores"],
    component: "ScoresPage",
    mechanism: "css",
    severity: "serious",
  },

  // ---------- /athletics/teams/:slug (TeamPage, tier M) ----------
  {
    id: "athletics-team-roster-headers-001",
    rule: "table-header-association",
    title: "Roster cells point to the wrong headers",
    description: "Roster cells use hard-coded headers attributes that are off by one column (the last points at a header that doesn't exist), so screen readers announce the wrong column.",
    fixDescription: "Removes the headers attributes and uses scope on the header cells.",
    pages: ["/athletics/teams/:slug"],
    component: "TeamPage",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-team-schedule-caption-001",
    rule: "table-no-caption",
    title: "Team schedule table has no caption",
    description: "The schedule and results table has no <caption>.",
    fixDescription: "Adds a caption with the team and season.",
    pages: ["/athletics/teams/:slug"],
    component: "TeamPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "athletics-team-conference-color-001",
    rule: "color-only-info",
    title: "Conference games are marked only by a gold stripe",
    description: "Conference games get a gold left border and nothing else, so the distinction is visual and color only.",
    fixDescription: "Adds a visible \"Conference\" label to those rows.",
    pages: ["/athletics/teams/:slug"],
    component: "TeamPage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "athletics-team-stats-small-001",
    rule: "text-small",
    title: "Team stat labels are 10px",
    description: "The labels in the team stats band are 10px uppercase text.",
    fixDescription: "Uses 0.95rem labels.",
    pages: ["/athletics/teams/:slug"],
    component: "TeamPage",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "athletics-team-video-title-001",
    rule: "iframe-missing-title",
    title: "Highlights video frame has no title",
    description: "The season highlights embed is an <iframe> with no title.",
    fixDescription: "Adds a title naming the video.",
    pages: TEAM_PAGES.filter((p) => !p.includes("basketball")),
    component: "VideoEmbed",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "athletics-team-schedule-pdf-001",
    rule: "link-document",
    title: "Printable schedule link doesn't say it's a PDF",
    description: "\"Printable schedule\" downloads a PDF with no file type or size.",
    fixDescription: "Adds the file type and size.",
    pages: ["/athletics/teams/mens-basketball"],
    component: "TeamPage",
    mechanism: "markup",
    severity: "minor",
  },

  // ---------- /athletics/athletes/:slug (tier L) ----------
  {
    id: "athletics-athlete-photo-alt-001",
    rule: "alt-suspicious",
    title: "Athlete photo alt text is just \"photo\"",
    description: "Every athlete headshot has alt=\"photo\", which says nothing about the image.",
    fixDescription: "Uses alt text describing the athlete's photo.",
    pages: ["/athletics/athletes/:slug"],
    component: "AthleteProfile",
    mechanism: "markup",
    severity: "minor",
  },
];
