import type { ScenarioDef } from "./types";

// /campus-map (tier T, plan 06 #10). A vendor-style SVG map widget bolted onto the flagship About template.
// CSS defects and fixes live in styles/features/campus-map.css.
const P = ["/campus-map"];
const s = (def: Omit<ScenarioDef, "pages">): ScenarioDef => ({ ...def, pages: P });

export const campusMapScenarios: ScenarioDef[] = [
  // ---------- Errors ----------
  s({
    id: "campus-map-building-name-001", rule: "svg-control-unlabeled",
    title: "Map buildings have no accessible name",
    description: "Each building is an SVG <path> with a click handler and no aria-label or <title>, so nothing names it.",
    fixDescription: "Each building shape gets an aria-label with its name and building code.",
    component: "CampusMapSvg", mechanism: "markup", severity: "critical",
  }),
  s({
    id: "campus-map-zoom-name-001", rule: "svg-control-unlabeled",
    title: "Zoom buttons are unnamed SVG icons",
    description: "The zoom in, zoom out and reset buttons contain only SVG icons with no text, title or aria-label.",
    fixDescription: "Names the buttons \"Zoom in\", \"Zoom out\" and \"Reset map view\".",
    component: "MapZoomControls", mechanism: "markup", severity: "critical",
  }),
  s({
    id: "campus-map-svg-role-001", rule: "svg-control-unlabeled",
    title: "Map SVG is role=\"img\" with no name",
    description: "The map <svg> carries role=\"img\" from a snippet but has no accessible name, and role=\"img\" hides every building inside it from assistive technology.",
    fixDescription: "The map becomes a named group (\"Interactive campus map\") so its buildings are exposed.",
    component: "CampusMapSvg", mechanism: "markup", severity: "serious",
  }),
  s({
    id: "campus-map-search-label-001", rule: "input-missing-label",
    title: "Building search box has only a placeholder",
    description: "The \"Find a building\" search input has a placeholder and no label.",
    fixDescription: "Adds a visible <label>.",
    component: "MapSearch", mechanism: "markup", severity: "critical",
  }),
  s({
    id: "campus-map-search-button-001", rule: "button-empty",
    title: "Search submit is an empty icon button",
    description: "The building search submit button shows a magnifier icon and has no text.",
    fixDescription: "Adds visually hidden text \"Search buildings\".",
    component: "MapSearch", mechanism: "markup", severity: "critical",
  }),
  s({
    id: "campus-map-category-label-001", rule: "select-missing-label",
    title: "Building type filter has no label",
    description: "The building type <select> sits next to the plain text \"Show:\" and has no label.",
    fixDescription: "\"Show building type\" becomes a <label> for the select.",
    component: "MapFilters", mechanism: "markup", severity: "critical",
  }),
  s({
    id: "campus-map-category-controls-001", rule: "aria-broken-reference",
    title: "Filter aria-controls points at a missing id",
    description: "The building type filter has aria-controls=\"map-buildings\", but the buildings layer's id is \"campus-map-buildings\".",
    fixDescription: "Points aria-controls at the real id.",
    component: "MapFilters", mechanism: "markup", severity: "serious",
  }),
  s({
    id: "campus-map-close-button-001", rule: "button-empty",
    title: "Detail panel close button has no name",
    description: "The building detail panel closes with a \"×\" icon button that has no accessible name.",
    fixDescription: "Adds visually hidden text \"Close building details\".",
    component: "BuildingDetail", mechanism: "markup", severity: "critical",
  }),
  s({
    id: "campus-map-detail-heading-empty-001", rule: "heading-empty",
    title: "Detail panel ships an empty heading",
    description: "Until a building is selected, the detail panel renders an empty <h2> placeholder.",
    fixDescription: "The empty state heading reads \"Building details\".",
    component: "BuildingDetail", mechanism: "markup", severity: "serious",
  }),
  s({
    id: "campus-map-legend-expanded-001", rule: "aria-invalid-value",
    title: "Legend toggle uses aria-expanded=\"yes\"",
    description: "The \"Map legend\" toggle sets aria-expanded to \"yes\" or \"no\", which aren't valid values, so its state is never announced.",
    fixDescription: "Uses aria-expanded=\"true\" and \"false\".",
    component: "MapLegend", mechanism: "markup", severity: "serious",
  }),
  s({
    id: "campus-map-lots-hidden-focus-001", rule: "aria-hidden-focusable",
    title: "Parking lot links are focusable inside aria-hidden",
    description: "The parking layer is wrapped in aria-hidden=\"true\" to quiet the map, but each lot is a focusable link, so keyboard users land on links that say nothing.",
    fixDescription: "Removes aria-hidden and names each lot link (\"Lot A, visitor and daily parking\").",
    component: "CampusMapSvg", mechanism: "markup", severity: "serious",
  }),
  s({
    id: "campus-map-duplicate-id-001", rule: "duplicate-id",
    title: "Building shapes and labels share ids",
    description: "The GIS export gives each building's <path> and its <text> label the same id (\"founders-hall\" twice, and so on).",
    fixDescription: "Labels no longer repeat the building's id.",
    component: "CampusMapSvg", mechanism: "markup", severity: "moderate",
  }),
  s({
    id: "campus-map-entrance-icon-alt-001", rule: "img-empty-alt-meaningful",
    title: "Accessible entrance icon has alt=\"\"",
    description: "In the detail panel, the only thing marking an entrance as accessible is a wheelchair icon with alt=\"\".",
    fixDescription: "The icon's alt text reads \"Accessible entrance\".",
    component: "BuildingDetail", mechanism: "markup", severity: "serious",
  }),

  // ---------- Alerts ----------
  s({
    id: "campus-map-aerial-alt-001", rule: "alt-suspicious",
    title: "Aerial backdrop alt text is a file name",
    description: "The decorative aerial illustration behind the map has alt=\"campus_aerial_FINAL_v3.jpg\".",
    fixDescription: "Marks the backdrop decorative (alt=\"\").",
    component: "CampusMapPage", mechanism: "markup", severity: "minor",
  }),
  s({
    id: "campus-map-parking-pdf-001", rule: "link-document",
    title: "Printable parking map doesn't say it's a PDF",
    description: "\"Printable parking map\" downloads a PDF with no file type or size.",
    fixDescription: "The link reads \"Parking Map (PDF, 3 KB)\".",
    component: "CampusMapPage", mechanism: "markup", severity: "minor",
  }),
  s({
    id: "campus-map-parking-window-001", rule: "link-new-window",
    title: "\"Parking Services\" opens a new tab without warning",
    description: "The Parking Services link opens a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\".",
    component: "CampusMapPage", mechanism: "markup", severity: "minor",
  }),
  s({
    id: "campus-map-print-link-001", rule: "link-javascript",
    title: "\"Print this map\" is a # link",
    description: "\"Print this map\" is <a href=\"#\"> with a click handler that calls window.print().",
    fixDescription: "Uses a real <button>.",
    component: "MapToolbar", mechanism: "markup", severity: "moderate",
  }),
  s({
    id: "campus-map-detail-more-001", rule: "link-generic",
    title: "Detail panel link says \"Learn more\"",
    description: "Every building's detail panel ends in a link reading only \"Learn more\".",
    fixDescription: "The link names its destination, e.g. \"Visit Sequoia Library\".",
    component: "BuildingDetail", mechanism: "markup", severity: "moderate",
  }),
  s({
    id: "campus-map-detail-heading-skip-001", rule: "heading-skipped",
    title: "Detail panel subheadings are <h5>",
    description: "\"Hours\", \"Entrances\" and \"In this building\" are <h5> directly under the panel's <h2>.",
    fixDescription: "They become <h3>.",
    component: "BuildingDetail", mechanism: "markup", severity: "moderate",
  }),
  s({
    id: "campus-map-directory-heading-001", rule: "heading-possible",
    title: "\"Major buildings\" is a bold paragraph",
    description: "The heading over the building directory table is a bold paragraph, not a heading.",
    fixDescription: "Makes it an <h2>.",
    component: "BuildingDirectory", mechanism: "markup", severity: "moderate",
  }),
  s({
    id: "campus-map-directory-caption-001", rule: "table-no-caption",
    title: "Building directory table has no caption",
    description: "The major buildings table has no <caption>.",
    fixDescription: "Adds a caption.",
    component: "BuildingDirectory", mechanism: "markup", severity: "minor",
  }),
  s({
    id: "campus-map-footnote-small-001", rule: "text-small",
    title: "Map footnote is 10px",
    description: "The \"not to scale\" and last-updated footnote under the map is 10px text.",
    fixDescription: "Uses 0.9rem.",
    component: "CampusMapPage", mechanism: "css", severity: "minor",
  }),
  s({
    id: "campus-map-tooltip-hover-001", rule: "event-handler-device",
    title: "Building name tooltips appear on hover only",
    description: "Hovering a building shows its name; focus never does.",
    fixDescription: "The tooltip also appears when a building has keyboard focus.",
    component: "CampusMapSvg", mechanism: "behavior", severity: "moderate",
    detectedBy: { manualOnly: true }, // ADR-030: React delegates events, so no onmouseover attribute exists.
  }),

  // ---------- Manual ----------
  s({
    id: "campus-map-building-keyboard-001", rule: "kbd-div-button",
    title: "Buildings are clickable paths with no keyboard access",
    description: "Buildings are <path onclick> elements with no role or tabindex, so they can't be reached or activated from the keyboard, and there is no other way to browse them.",
    fixDescription: "Buildings get role=\"button\", tabindex=\"0\" and Enter/Space activation, and a parallel list of building buttons appears under the map.",
    component: "CampusMapSvg", mechanism: "behavior", severity: "critical",
  }),
  s({
    id: "campus-map-pan-drag-001", rule: "kbd-drag-no-alternative",
    title: "The map pans only by dragging",
    description: "Panning works only by dragging with a pointer; there are no pan buttons and the keyboard can't move the map.",
    fixDescription: "The map takes focus and pans with the arrow keys (+ and − zoom), and four named pan buttons are added.",
    component: "CampusMapSvg", mechanism: "behavior", severity: "serious",
  }),
  s({
    id: "campus-map-detail-announce-001", rule: "sr-status-not-announced",
    title: "Selecting a building updates the panel silently",
    description: "Selecting a building fills the detail panel beside the map, but nothing is announced and focus stays put.",
    fixDescription: "Focus moves to the panel's heading when a building is selected.",
    component: "BuildingDetail", mechanism: "behavior", severity: "serious",
  }),
  s({
    id: "campus-map-close-focus-001", rule: "focus-lost-on-update",
    title: "Closing the panel drops focus to the page",
    description: "The close button removes itself, so focus falls back to the top of the page.",
    fixDescription: "Focus returns to the building that opened the panel.",
    component: "BuildingDetail", mechanism: "behavior", severity: "serious",
  }),
  s({
    id: "campus-map-parking-legend-001", rule: "color-only-info",
    title: "Parking permit types are shown by color only",
    description: "Lots are purple, green or orange by permit type, and the legend shows only the color swatches with no text.",
    fixDescription: "The legend labels each color (visitor and daily, general, resident).",
    component: "MapLegend", mechanism: "markup", severity: "serious",
  }),
  s({
    id: "campus-map-layers-state-001", rule: "sr-visual-only-state",
    title: "Layer chips show on/off by color only",
    description: "The \"Parking\" and \"Accessible entrances\" layer chips change color when on, but expose no pressed state.",
    fixDescription: "Adds aria-pressed and a check mark.",
    component: "MapFilters", mechanism: "markup", severity: "serious",
  }),
  s({
    id: "campus-map-layers-contrast-001", rule: "contrast-ui-low",
    title: "Layer chip borders are nearly invisible",
    description: "Unselected layer chips have a #d4d4d4 border on white (about 1.5:1).",
    fixDescription: "Uses a #8f8f8f border, just above the 3:1 minimum.",
    component: "MapFilters", mechanism: "css", severity: "moderate",
  }),
  s({
    id: "campus-map-results-count-001", rule: "sr-results-no-live-region",
    title: "Filter result count isn't announced",
    description: "\"Showing 30 buildings\" updates when the filter changes, but it isn't a live region.",
    fixDescription: "The count is a role=\"status\" live region.",
    component: "MapFilters", mechanism: "markup", severity: "moderate",
  }),
  s({
    id: "campus-map-labels-contrast-001", rule: "contrast-text-low",
    title: "Building code labels are pale on the map",
    description: "Building code labels are #8fae93 on the pale green map (about 2.2:1).",
    fixDescription: "Uses #4c7152, just above the 4.5:1 minimum.",
    component: "CampusMapSvg", mechanism: "css", severity: "serious",
  }),
  s({
    id: "campus-map-focus-indicator-001", rule: "focus-indicator-missing",
    title: "Map controls hide the focus outline",
    description: "The map widget's stylesheet sets outline: none on every control inside it.",
    fixDescription: "Restores a visible focus outline, including on buildings.",
    component: "CampusMap", mechanism: "css", severity: "serious",
  }),
  s({
    id: "campus-map-zoom-tabindex-001", rule: "focus-positive-tabindex",
    title: "Zoom buttons have tabindex=\"1\"",
    description: "The zoom buttons carry tabindex=\"1\", so they come before the skip link and the site header in the tab order.",
    fixDescription: "Removes the positive tabindex.",
    component: "MapZoomControls", mechanism: "markup", severity: "moderate",
  }),
  s({
    id: "campus-map-focus-order-001", rule: "focus-order-mismatch",
    title: "Map tools come after the map in the tab order",
    description: "Search and filters sit to the left of the map but come after the map and detail panel in the source, so focus jumps around.",
    fixDescription: "The tools come first in the source, matching the visual order.",
    component: "CampusMap", mechanism: "markup", severity: "moderate",
  }),
  s({
    id: "campus-map-reflow-001", rule: "reflow-horizontal-scroll",
    title: "Map is a fixed 52rem wide",
    description: "The map viewport is a fixed 52rem (832 px) wide, so small screens and 400% zoom scroll the whole page sideways.",
    fixDescription: "The map scales to the width of its column.",
    component: "CampusMap", mechanism: "css", severity: "serious",
  }),
  s({
    id: "campus-map-marker-motion-001", rule: "motion-ignores-reduced-motion",
    title: "\"You are here\" marker pulses forever",
    description: "The \"You are here\" marker pulses continuously, even when the visitor has asked for reduced motion.",
    fixDescription: "The pulse stops under prefers-reduced-motion.",
    component: "CampusMapSvg", mechanism: "css", severity: "minor",
  }),
];
