import type { ScenarioDef } from "./types";

/** Events with registration still open on SITE_NOW, i.e. the pages that render the registration form (ADR-028). */
const REGISTRATION_PAGES = ["research-symposium-2026", "homecoming-2026", "fall-choral-concert", "basketball-home-opener", "admissions-open-house", "redwood-lecture-climate"].map((s) => `/events/${s}`);

// Events calendar (third-party vendor widget look), including the registration form on /events/:slug.
export const eventsScenarios: ScenarioDef[] = [
  // ---------- /events (month grid) ----------
  {
    id: "events-cal-chip-state-001",
    rule: "sr-visual-only-state",
    title: "Category chips show the active filter by color only",
    description: "The selected category chip is only filled blue; the buttons expose no pressed state to assistive technology.",
    fixDescription: "Adds aria-pressed to each chip.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "events-cal-nav-empty-001",
    rule: "button-empty",
    title: "Previous and next month buttons have no name",
    description: "The ‹ and › month buttons contain only decorative glyphs, so they are announced as \"button\".",
    fixDescription: "Adds visually hidden \"Previous month\" and \"Next month\" text.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "events-cal-month-status-001",
    rule: "sr-status-not-announced",
    title: "Month change is not announced",
    description: "Changing the month redraws the grid and the month title silently.",
    fixDescription: "Makes the month title a role=\"status\" live region.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "behavior",
    severity: "moderate",
  },
  {
    id: "events-cal-headers-001",
    rule: "table-header-association",
    title: "Day cells reference weekday ids that don't exist",
    description: "Each day cell has headers=\"cal-sun\" (and so on), but the weekday headers are wd-0 to wd-6, so cells are associated with nothing.",
    fixDescription: "Removes the stale headers attributes and scopes the weekday headers to their columns.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "events-cal-today-aria-001",
    rule: "aria-invalid-value",
    title: "Today's cell uses aria-current=\"yes\"",
    description: "The vendor marks today with aria-current=\"yes\", which is not a valid token.",
    fixDescription: "Uses aria-current=\"date\".",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "events-cal-caption-001",
    rule: "table-no-caption",
    title: "Calendar table has no caption",
    description: "The month name sits above the table in a paragraph; the table itself has no caption.",
    fixDescription: "Adds a caption naming the month.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "events-cal-day-click-001",
    rule: "kbd-div-button",
    title: "Days are selected by clicking the table cell",
    description: "A day's event list opens from an onclick on the <td>. The cell is not focusable and has no role, so keyboard users can't select a day.",
    fixDescription: "Puts a real <button> (with the event count) in each day that has events.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "events-cal-color-only-001",
    rule: "color-only-info",
    title: "Event category shown by colored dot only",
    description: "Each event in the grid has a colored dot for its category, with no text or legend.",
    fixDescription: "Adds a short category tag to each event and a key below the grid.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "events-cal-link-title-001",
    rule: "title-redundant",
    title: "Event links repeat their text in a title",
    description: "Every event link in the grid has a title attribute identical to its text.",
    fixDescription: "Removes the redundant title attributes.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "events-cal-text-small-001",
    rule: "text-small",
    title: "Event names in the grid are 10px",
    description: "The vendor stylesheet sets event names in day cells to 10px.",
    fixDescription: "Uses 0.85rem.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "events-cal-reflow-001",
    rule: "reflow-horizontal-scroll",
    title: "Calendar forces horizontal scrolling",
    description: "The grid has a 56rem minimum width, so at 320 CSS px (400% zoom) the whole page scrolls sideways.",
    fixDescription: "Lets the table shrink to the viewport with wrapping event names.",
    pages: ["/events"],
    component: "EventsCalendar",
    mechanism: "css",
    severity: "serious",
  },

  // ---------- /events/search ----------
  {
    id: "events-search-keyword-label-001",
    rule: "input-missing-label",
    title: "Keyword box has no label",
    description: "\"Keyword\" is a <span> above the search box, not a <label>.",
    fixDescription: "Uses a <label for> on the input.",
    pages: ["/events/search"],
    component: "EventsSearch",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "events-search-date-label-001",
    rule: "label-for-mismatch",
    title: "Date labels point at the wrong ids",
    description: "The \"From\" and \"To\" labels use for=\"evs-from-input\" and for=\"evs-to-input\", but the inputs are evs-from and evs-to.",
    fixDescription: "Points each label at its date input.",
    pages: ["/events/search"],
    component: "EventsSearch",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "events-search-fieldset-001",
    rule: "fieldset-missing",
    title: "Category checkboxes aren't grouped",
    description: "The category checkboxes follow a plain \"Category\" paragraph, with no fieldset or legend.",
    fixDescription: "Wraps them in a fieldset with the legend \"Category\".",
    pages: ["/events/search"],
    component: "EventsSearch",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "events-search-results-live-001",
    rule: "sr-results-no-live-region",
    title: "Result count updates silently",
    description: "After Search or Reset the \"N events found\" line changes with no announcement.",
    fixDescription: "Makes the count a role=\"status\" live region.",
    pages: ["/events/search"],
    component: "EventsSearch",
    mechanism: "behavior",
    severity: "moderate",
  },

  // ---------- /events/category/:slug ----------
  {
    id: "events-category-img-alt-001",
    rule: "img-missing-alt",
    title: "Event thumbnails have no alt attribute",
    description: "Listing thumbnails are output without an alt attribute.",
    fixDescription: "Marks them decorative (alt=\"\"); the event title follows.",
    pages: ["/events/category/:slug"],
    component: "EventsCategory",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "events-category-details-001",
    rule: "link-generic",
    title: "Every event ends in a \"Details\" link",
    description: "Each listing has an identical \"Details\" link.",
    fixDescription: "Adds the event title as visually hidden link text.",
    pages: ["/events/category/:slug"],
    component: "EventsCategory",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "events-category-meta-contrast-001",
    rule: "contrast-text-low",
    title: "Date, place and cost lines are pale blue-gray",
    description: "Event meta lines are #93a3b8 on white (about 2.6:1).",
    fixDescription: "Uses #4a5a70 (about 7:1).",
    pages: ["/events/category/:slug"],
    component: "EventsCategory",
    mechanism: "css",
    severity: "serious",
  },

  // ---------- /events/:slug (EventPage) ----------
  {
    id: "events-detail-img-alt-001",
    rule: "alt-suspicious",
    title: "Event photo alt is the upload file name",
    description: "The event photo's alt text is the file name, e.g. \"fall-fest-2026_FINAL_web.jpg\".",
    fixDescription: "Describes the photo.",
    pages: ["/events/:slug"],
    component: "EventPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "events-detail-facts-table-001",
    rule: "table-layout",
    title: "Event facts use a layout table",
    description: "When, Where, Cost and Capacity are laid out in a borderless table with no headers.",
    fixDescription: "Uses a description list (<dl>).",
    pages: ["/events/:slug"],
    component: "EventPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "events-detail-directions-001",
    rule: "link-new-window",
    title: "\"Get directions\" opens a new tab without warning",
    description: "The directions link opens the campus map in a new tab with no indication.",
    fixDescription: "Adds \"(opens in a new tab)\" to the link.",
    pages: ["/events/:slug"],
    component: "EventPage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "events-detail-access-heading-001",
    rule: "heading-possible",
    title: "\"Accessibility\" subheading is a bold paragraph",
    description: "On events with an accessibility note, the \"Accessibility\" label is bold text rather than a heading.",
    fixDescription: "Makes it an <h2>.",
    pages: ["/events/fall-fest-2026", "/events/homecoming-2026", "/events/basketball-home-opener", "/events/redwood-lecture-climate"],
    component: "EventPage",
    mechanism: "markup",
    severity: "moderate",
  },

  // ---------- /events/:slug registration form (plan 06 #6): events whose registration is still open ----------
  { id: "events-reg-stepper-001", rule: "kbd-div-button", title: "Attendee stepper works by mouse only", description: "The attendee count is a <span> between − and + <span>s with click handlers: they can't be focused, have no role or name, and the count isn't a form control.", fixDescription: "Uses a labeled number input with − and + buttons named \"Remove one attendee\" and \"Add one attendee\".", pages: REGISTRATION_PAGES, component: "RegistrationForm", mechanism: "behavior", severity: "serious" },
  { id: "events-reg-required-001", rule: "color-only-required", title: "Required fields marked only by a red asterisk", description: "Name and email carry a small red \"*\" that is never explained, and the inputs aren't marked required in code.", fixDescription: "Writes \"(required)\" in the labels and sets aria-required.", pages: REGISTRATION_PAGES, component: "RegistrationForm", mechanism: "markup", severity: "moderate" },
  { id: "events-reg-errors-001", rule: "form-vague-errors", title: "Every error says \"Invalid input\"", description: "An empty name or a malformed email both show \"Invalid input\" in red under the field, with no hint of what to fix; the message isn't tied to the input.", fixDescription: "Specific messages (\"Enter an email address in the format name@example.com.\") linked with aria-describedby and aria-invalid; focus moves to the first problem.", pages: REGISTRATION_PAGES, component: "RegistrationForm", mechanism: "behavior", severity: "serious" },
  { id: "events-reg-confirm-001", rule: "sr-status-not-announced", title: "Registration confirmation appears silently", description: "After Register, the form is replaced by the confirmation number with no announcement, and focus is left on nothing.", fixDescription: "The confirmation is a role=\"status\" region and receives focus.", pages: REGISTRATION_PAGES, component: "RegistrationForm", mechanism: "behavior", severity: "moderate" },
];
