import type { ScenarioDef } from "./types";

export const homeScenarios: ScenarioDef[] = [
  {
    id: "home-page-title-001",
    rule: "page-title-missing",
    title: "Home page title is empty",
    description: "The home page ships an empty <title>, so the tab and history entry have no name.",
    fixDescription: "Sets the title to \"Redwood State University\".",
    pages: ["/"],
    component: "HomePage",
    mechanism: "document",
    severity: "serious",
  },
  {
    id: "home-hero-img-alt-001",
    rule: "img-missing-alt",
    title: "Hero photo has no alt attribute",
    description: "The home hero photo has no alt attribute, so screen readers may announce the file name.",
    fixDescription: "Adds alt text describing the photo.",
    pages: ["/"],
    component: "Hero",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "home-program-finder-label-001",
    rule: "input-missing-label",
    title: "Program finder input has no label",
    description: "The visible \"Find your program\" text is a paragraph, not a <label>, so the input has no accessible name.",
    fixDescription: "Turns the text into a <label> associated with the input.",
    pages: ["/"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "home-card-heading-skip-001",
    rule: "heading-skipped",
    title: "Card titles skip a heading level",
    description: "Explore cards use <h4> directly under an <h2>, skipping <h3>.",
    fixDescription: "Card titles become <h3>.",
    pages: ["/"],
    component: "Card",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "home-card-img-alt-suspicious-001",
    rule: "alt-suspicious",
    title: "Card photos use file names as alt text",
    description: "Explore card photos have alt text copied from the upload file name (\"IMG_2041.jpg\").",
    fixDescription: "Marks the photos decorative (alt=\"\") because the card title already names the link.",
    pages: ["/"],
    component: "Card",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "home-intro-justified-001",
    rule: "text-justified",
    title: "Welcome text is fully justified",
    description: "The welcome paragraph uses text-align: justify, creating uneven word spacing that is hard to read.",
    fixDescription: "Left-aligns the paragraph.",
    pages: ["/"],
    component: "HomePage",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "home-card-meta-contrast-001",
    rule: "contrast-text-low",
    title: "Card category labels have low contrast",
    description: "The small uppercase category label on each card is light gray (#a8a8a0, about 2.4:1).",
    fixDescription: "Uses the muted text token (#5c5c56, about 6.6:1).",
    pages: ["/"],
    component: "Card",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "home-card-focus-001",
    rule: "focus-indicator-missing",
    title: "Card links hide the focus outline",
    description: "Explore card links set outline: none on focus, so keyboard users cannot see where they are.",
    fixDescription: "Restores a visible focus outline.",
    pages: ["/"],
    component: "Card",
    mechanism: "css",
    severity: "serious",
  },
  // ---------- Plan 05 homepage sections (CSS in styles/sections/home.css) ----------
  {
    id: "home-audience-aria-ref-001",
    rule: "aria-broken-reference",
    title: "Audience navigation points at a missing heading id",
    description: "The \"Find your path\" navigation uses aria-labelledby=\"audiences-heading\", but the heading id is \"audience-heading\", so the landmark has no name.",
    fixDescription: "Points aria-labelledby at the heading's real id.",
    pages: ["/"],
    component: "AudiencePaths",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "home-audience-contrast-001",
    rule: "contrast-text-low",
    title: "White text on gold audience tiles",
    description: "Audience path tiles use white text on the brand gold (#c9a227), about 2.8:1.",
    fixDescription: "Uses near-black text (#1a1a18) on the gold (about 6.2:1).",
    pages: ["/"],
    component: "AudiencePaths",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "home-news-readmore-001",
    rule: "link-generic",
    title: "News teasers end in \"Read more\"",
    description: "Every news teaser ends with a link reading only \"Read more\".",
    fixDescription: "The link text names the story.",
    pages: ["/"],
    component: "HomeNews",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "home-news-link-redundant-001",
    rule: "link-redundant",
    title: "News photo and headline are separate links to the same story",
    description: "Each news photo is its own link to the story right next to the headline link, adding a redundant tab stop.",
    fixDescription: "The photo is no longer a link and is marked decorative.",
    pages: ["/"],
    component: "HomeNews",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "home-events-list-001",
    rule: "list-structure",
    title: "Event list items have no list",
    description: "Upcoming events are <li> elements inside a <div>, so they aren't announced as a list.",
    fixDescription: "Wraps the events in a <ul>.",
    pages: ["/"],
    component: "HomeEvents",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "home-events-calendar-window-001",
    rule: "link-new-window",
    title: "\"Full calendar\" opens a new tab without warning",
    description: "The link to the full events calendar opens in a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\".",
    pages: ["/"],
    component: "HomeEvents",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "home-tour-iframe-title-001",
    rule: "iframe-missing-title",
    title: "Campus tour video frame has no title",
    description: "The campus tour video is an <iframe> with no title attribute.",
    fixDescription: "Adds a title naming the video.",
    pages: ["/"],
    component: "VideoEmbed",
    mechanism: "markup",
    severity: "serious",
  },
];
