import type { ScenarioDef } from "./types";

export const homeScenarios: ScenarioDef[] = [
  {
    id: "home-page-title-001",
    rule: "page-title-missing",
    title: "Home page title is empty",
    description: "The home page ships an empty <title>, so the tab and history entry have no name.",
    fixDescription: "Sets the title to \"Redwood State University\".",
    pages: ["/"],
    component: "HomePage",
    mechanism: "document",
    severity: "serious",
  },
  {
    id: "home-hero-img-alt-001",
    rule: "img-missing-alt",
    title: "Hero photo has no alt attribute",
    description: "The home hero photo has no alt attribute, so screen readers may announce the file name.",
    fixDescription: "Adds alt text describing the photo.",
    pages: ["/"],
    component: "Hero",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "home-program-finder-label-001",
    rule: "input-missing-label",
    title: "Program finder input has no label",
    description: "The visible \"Find your program\" text is a paragraph, not a <label>, so the input has no accessible name.",
    fixDescription: "Turns the text into a <label> associated with the input.",
    pages: ["/"],
    component: "ProgramFinder",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "home-card-heading-skip-001",
    rule: "heading-skipped",
    title: "Card titles skip a heading level",
    description: "Explore cards use <h4> directly under an <h2>, skipping <h3>.",
    fixDescription: "Card titles become <h3>.",
    pages: ["/"],
    component: "Card",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "home-card-img-alt-suspicious-001",
    rule: "alt-suspicious",
    title: "Card photos use file names as alt text",
    description: "Explore card photos have alt text copied from the upload file name (\"IMG_2041.jpg\").",
    fixDescription: "Marks the photos decorative (alt=\"\") because the card title already names the link.",
    pages: ["/"],
    component: "Card",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "home-intro-justified-001",
    rule: "text-justified",
    title: "Welcome text is fully justified",
    description: "The welcome paragraph uses text-align: justify, creating uneven word spacing that is hard to read.",
    fixDescription: "Left-aligns the paragraph.",
    pages: ["/"],
    component: "HomePage",
    mechanism: "css",
    severity: "minor",
  },
  {
    id: "home-card-meta-contrast-001",
    rule: "contrast-text-low",
    title: "Card category labels have low contrast",
    description: "The small uppercase category label on each card is light gray (#a8a8a0, about 2.4:1).",
    fixDescription: "Uses #767676, just above the 4.5:1 minimum.",
    pages: ["/"],
    component: "Card",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "home-card-focus-001",
    rule: "focus-indicator-missing",
    title: "Card links hide the focus outline",
    description: "Explore card links set outline: none on focus, so keyboard users cannot see where they are.",
    fixDescription: "Restores a visible focus outline.",
    pages: ["/"],
    component: "Card",
    mechanism: "css",
    severity: "serious",
  },
  // ---------- Plan 05 homepage sections (CSS in styles/sections/home.css) ----------
  {
    id: "home-audience-aria-ref-001",
    rule: "aria-broken-reference",
    title: "Audience navigation points at a missing heading id",
    description: "The \"Find your path\" navigation uses aria-labelledby=\"audiences-heading\", but the heading id is \"audience-heading\", so the landmark has no name.",
    fixDescription: "Points aria-labelledby at the heading's real id.",
    pages: ["/"],
    component: "AudiencePaths",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "home-audience-contrast-001",
    rule: "contrast-text-low",
    title: "White text on gold audience tiles",
    description: "Audience path tiles use white text on the brand gold (#c9a227), about 2.8:1.",
    fixDescription: "Uses #3a3a34, just above the 4.5:1 minimum.",
    pages: ["/"],
    component: "AudiencePaths",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "home-news-readmore-001",
    rule: "link-generic",
    title: "News teasers end in \"Read more\"",
    description: "Every news teaser ends with a link reading only \"Read more\".",
    fixDescription: "The link text names the story.",
    pages: ["/"],
    component: "HomeNews",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "home-news-link-redundant-001",
    rule: "link-redundant",
    title: "News photo and headline are separate links to the same story",
    description: "Each news photo is its own link to the story right next to the headline link, adding a redundant tab stop.",
    fixDescription: "The photo is no longer a link and is marked decorative.",
    pages: ["/"],
    component: "HomeNews",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "home-events-list-001",
    rule: "list-structure",
    title: "Event list items have no list",
    description: "Upcoming events are <li> elements inside a <div>, so they aren't announced as a list.",
    fixDescription: "Wraps the events in a <ul>.",
    pages: ["/"],
    component: "HomeEvents",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "home-events-calendar-window-001",
    rule: "link-new-window",
    title: "\"Full calendar\" opens a new tab without warning",
    description: "The link to the full events calendar opens in a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\".",
    pages: ["/"],
    component: "HomeEvents",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "home-tour-iframe-title-001",
    rule: "iframe-missing-title",
    title: "Campus tour video frame has no title",
    description: "The campus tour video is an <iframe> with no title attribute.",
    fixDescription: "Adds a title naming the video.",
    pages: ["/"],
    component: "VideoEmbed",
    mechanism: "markup",
    severity: "serious",
  },
  // ---------- Plan 06 #11: hero carousel and announcement ticker (CSS in styles/features/carousel.css) ----------
  {
    id: "home-carousel-pause-001",
    rule: "motion-autorotate-no-pause",
    title: "Hero carousel rotates every 6 seconds with no pause",
    description: "The hero carousel advances every 6 seconds forever. There is no pause button, it keeps moving while hovered or focused, and it ignores prefers-reduced-motion.",
    fixDescription: "Adds a Pause/Play button, stops rotating while hovered or focused, and doesn't auto-rotate (or cross-fade) under reduced motion.",
    pages: ["/"],
    component: "HeroCarousel",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "home-carousel-controls-kbd-001",
    rule: "kbd-carousel-unreachable",
    title: "Carousel arrows and dots can't be reached by keyboard",
    description: "The previous, next and slide dots are <span> elements with click handlers, so keyboard users can't change slides.",
    fixDescription: "They become named <button>s (\"Previous slide\", \"Next slide\", \"Slide 2 of 5\"), with the current dot marked aria-current.",
    pages: ["/"],
    component: "HeroCarousel",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "home-carousel-focus-001",
    rule: "focus-unexpected-move",
    title: "Every slide change moves focus to the new slide",
    description: "Each slide change, including the automatic ones, focuses the new slide, so wherever a keyboard user was on the page, focus jumps back to the carousel every 6 seconds.",
    fixDescription: "Slide changes never move focus; the slide group is labeled \"Slide N of 5\" instead.",
    pages: ["/"],
    component: "HeroCarousel",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "home-ticker-motion-001",
    rule: "motion-animated-announcement",
    title: "Announcement ticker scrolls with no way to stop it",
    description: "The campus announcements strip scrolls sideways continuously, with no pause control, and keeps moving under prefers-reduced-motion.",
    fixDescription: "Adds a Pause button, stops on hover and focus, and shows a static list under reduced motion.",
    pages: ["/"],
    component: "AnnouncementTicker",
    mechanism: "behavior",
    severity: "moderate",
  },
  // ---------- Key Dates table (added at the user's request for more, severe, sighted-invisible errors) ----------
  {
    id: "home-dates-table-headers-001",
    rule: "table-header-association",
    title: "Key dates table has no real header cells",
    description: "The Date/Event/Details header row uses <td>, styled to look identical to a header, so a screen reader reading down a column never announces what it means.",
    fixDescription: "The header row becomes real <th scope=\"col\"> cells.",
    pages: ["/"],
    component: "KeyDatesTable",
    mechanism: "markup",
    severity: "serious",
    // The rule's default axe id (td-headers-attr) checks headers="..." references that don't resolve; a
    // table with no <th>/headers attributes at all doesn't trip it. WAVE's th_empty still catches this.
    detectedBy: { wave: ["th_empty"] },
  },
  {
    id: "home-dates-table-sort-value-001",
    rule: "aria-invalid-value",
    title: "Date column's aria-sort is \"asc\"",
    description: "The Date header sets aria-sort=\"asc\"; the only valid values are ascending/descending/other/none, so assistive tech ignores it silently.",
    fixDescription: "Uses aria-sort=\"ascending\".",
    pages: ["/"],
    component: "KeyDatesTable",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "home-dates-table-region-typo-001",
    rule: "aria-invalid-attr",
    title: "Table region uses aria-labeledby (one L)",
    description: "The table's wrapping region is misspelled aria-labeledby instead of aria-labelledby, so the region has no accessible name at all.",
    fixDescription: "Corrects the attribute name.",
    pages: ["/"],
    component: "KeyDatesTable",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "home-dates-table-action-dupid-001",
    rule: "duplicate-id",
    title: "Every row's \"Details\" button shares one id",
    description: "Each row's Details button is aria-labelledby=\"dates-row-detail\", and every row also renders a hidden span with that same id, so the browser resolves every button's accessible name to the first row's text.",
    fixDescription: "Gives each row's hidden label its own id (\"dates-row-detail-0\", \"-1\", …).",
    pages: ["/"],
    component: "KeyDatesTable",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "home-dates-table-filter-tab-001",
    rule: "aria-required-parent",
    title: "Filter pills use role=\"tab\" with no tablist",
    description: "The All/Academic/Financial filter buttons are role=\"tab\", but their container has no role=\"tablist\", so screen readers don't announce the tab pattern (selection, count) at all.",
    fixDescription: "Adds role=\"tablist\" to the container.",
    pages: ["/"],
    component: "KeyDatesTable",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "home-dates-table-urgent-icon-001",
    rule: "img-empty-alt-meaningful",
    title: "\"Deadline is approaching\" icon has alt=\"\"",
    description: "The warning icon next to the nearest deadline is the only thing marking it urgent, and it has alt=\"\".",
    fixDescription: "Gives the icon alt=\"Deadline is approaching\".",
    pages: ["/"],
    component: "KeyDatesTable",
    mechanism: "markup",
    severity: "serious",
  },
  // ---------- "Take the campus tour" companion ----------
  {
    id: "home-tour-share-svg-001",
    rule: "svg-control-unlabeled",
    title: "Share button is an unlabeled SVG icon",
    description: "The share button next to the campus tour video is only an SVG icon, with no accessible name.",
    fixDescription: "Adds aria-label=\"Share this video\".",
    pages: ["/"],
    component: "TourShareButton",
    mechanism: "markup",
    severity: "serious",
    // The icon is aria-hidden, so axe's svg-img-alt check (aimed at SVGs presented as images) doesn't apply;
    // only the button's own missing accessible name (button-name) fires.
    detectedBy: { axe: ["button-name"] },
  },
  // ---------- Hero carousel companion ----------
  {
    id: "home-hero-cta-hidden-001",
    rule: "aria-hidden-focusable",
    title: "Hero's secondary button is hidden from screen readers",
    description: "Slide 1's \"Plan a visit\" button sits inside an aria-hidden=\"true\" wrapper, so it's fully visible and clickable but invisible to assistive tech; a keyboard user can still tab to it and hear nothing.",
    fixDescription: "Removes the aria-hidden wrapper.",
    pages: ["/"],
    component: "HeroCarousel",
    mechanism: "markup",
    severity: "critical",
  },
  // ---------- Newsletter signup ----------
  {
    id: "home-newsletter-heading-empty-001",
    rule: "heading-empty",
    title: "\"Stay Connected\" heading is empty",
    description: "The newsletter section's <h2> has no text; a background image supplies the visible wordmark, so sighted users see a heading but screen readers announce \"heading, blank\".",
    fixDescription: "The heading renders its real text.",
    pages: ["/"],
    component: "NewsletterSignup",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "home-newsletter-label-mismatch-001",
    rule: "label-for-mismatch",
    title: "\"Email address\" label points at a hidden honeypot field",
    description: "The visible \"Email address\" label's for attribute targets a hidden anti-spam field, not the real email input right next to it, so a screen reader announces the wrong purpose for both fields.",
    fixDescription: "Points the label's for at the real email input.",
    pages: ["/"],
    component: "NewsletterSignup",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "home-newsletter-frequency-select-001",
    rule: "select-missing-label",
    title: "Frequency dropdown has no associated label",
    description: "The Weekly/Monthly <select> sits next to a plain \"How often?\" span instead of a <label>, so it has no accessible name.",
    fixDescription: "Turns the caption into a <label for>.",
    pages: ["/"],
    component: "NewsletterSignup",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "home-newsletter-subscribe-image-001",
    rule: "input-image-no-alt",
    title: "Subscribe button is an <input type=\"image\"> with no alt",
    description: "The form's submit control is an image input with no alt attribute, so it has no accessible name and screen readers may announce the image URL instead.",
    fixDescription: "Replaces it with a real <button>Subscribe</button>.",
    pages: ["/"],
    component: "NewsletterSignup",
    mechanism: "markup",
    severity: "critical",
  },
];
