import type { RuleKey } from "../rules";
import type { ScenarioDef } from "./types";

type Mech = ScenarioDef["mechanism"];
type Sev = NonNullable<ScenarioDef["severity"]>;
const d = (id: string, rule: RuleKey, component: string, mechanism: Mech, severity: Sev, title: string, description: string, fixDescription: string): ScenarioDef =>
  ({ id: `legacy-aid-${id}-001`, rule, pages: ["/financial-aid/legacy-application"], component, mechanism, severity, title, description, fixDescription });

// /financial-aid/legacy-application: Legacy Financial Aid Form, one of the six terrible pages (plan 06 #9, plan 07).
// A ~2006 page dropped into the new site. Tier T.
export const legacyAidScenarios: ScenarioDef[] = [
  // ---------- Errors ----------
  d("page-title", "page-title-missing", "LegacyAidPage", "document", "serious",
    "Page has an empty <title>", "The old form template ships with an empty <title>, so the tab and history entry have no name.", "Sets the title to \"Institutional Aid Application | Redwood State University\"."),
  d("banner-alt", "img-missing-alt", "LegacyBanner", "markup", "serious",
    "Banner image has no alt attribute", "The \"Office of Financial Aid, Online Services\" banner is an image with no alt attribute.", "Adds alt text with the banner's words."),
  d("nav-list", "list-structure", "LegacyNav", "markup", "moderate",
    "Left navigation <li> items sit in a <div>", "The side menu's <li> elements have no <ul> parent.", "Wraps the items in a <ul>."),
  d("fields-label", "input-missing-label", "LegacyForm", "markup", "critical",
    "Text boxes have no labels", "Every text box is labelled only by text in the table cell to its left; nothing is associated with the inputs (including the certification checkbox and the security code box).", "Each prompt is a <label for> its input."),
  d("selects-label", "select-missing-label", "LegacyForm", "markup", "critical",
    "Date of birth and term selects are unlabeled", "The month, day and year selects and the aid term select have no labels.", "Adds labels (date parts are grouped in a fieldset)."),
  d("explain-for", "label-for-mismatch", "LegacyForm", "markup", "serious",
    "Explanation label points at the wrong id", "The \"Explain your circumstances\" label has for=\"explain\" but the textarea's id is \"explanation\".", "The label's for matches the textarea."),
  d("image-submit", "input-image-no-alt", "LegacyForm", "markup", "critical",
    "Image submit button has no alt", "The form is submitted with <input type=\"image\"> showing a \"SUBMIT\" graphic and no alt attribute.", "Adds alt=\"Submit application\"."),
  d("captcha-alt", "img-missing-alt", "LegacyCaptcha", "markup", "critical",
    "CAPTCHA image has no alternative", "The security code is an image with no alt and no audio or text alternative, so a blind user cannot submit the form.", "Adds alt text and a text question (\"What is 4 plus 3?\") that the same box also accepts."),
  d("captcha-refresh", "link-empty", "LegacyCaptcha", "markup", "serious",
    "\"New image\" link is an image with empty alt", "The refresh control is a link wrapping an arrow image with alt=\"\", so the link has no name.", "Gives the image alt=\"Show a different security image\"."),
  d("household-headers", "table-header-association", "LegacyHousehold", "markup", "serious",
    "Household table cells point at missing headers", "Cells in the household members table use headers=\"hh_name\" etc., but the header ids are hh-name.", "headers attributes match the <th> ids."),
  d("household-inputs", "input-missing-label", "LegacyHousehold", "markup", "critical",
    "Household table inputs have no names", "The 12 inputs in the household members table have no label or accessible name.", "Each input gets an aria-label such as \"Member 1 name\"."),
  d("heading-empty", "heading-empty", "LegacyAidPage", "markup", "moderate",
    "Empty <h2> used as a spacer", "An empty <h2> below the banner adds vertical space.", "Removes it; spacing comes from CSS."),
  d("duplicate-phone-id", "duplicate-id", "LegacyForm", "markup", "moderate",
    "Home and cell phone share id=\"phone\"", "Both phone boxes were copied from one row and both have id=\"phone\".", "Uses phone-home and phone-cell."),

  // ---------- Alerts ----------
  d("layout-table", "table-layout", "LegacyAidPage", "markup", "moderate",
    "Whole page is laid out with tables", "The banner, menu, form rows and buttons are positioned with nested <table> elements.", "Uses <div>s with CSS layout."),
  d("text-small", "text-small", "LegacyAidPage", "markup", "moderate",
    "Instructions are 10px Verdana", "Inline font styles set the instructions and field notes at 10px.", "Uses the site's body size."),
  d("help-javascript", "link-javascript", "LegacyForm", "markup", "moderate",
    "\"Help\" links are href=\"#\" links", "The [Help] links next to fields are <a href=\"#\"> with click handlers that toggle help text.", "Uses <button aria-expanded> controls."),
  d("enroll-fieldset", "fieldset-missing", "LegacyForm", "markup", "moderate",
    "Enrollment status radios are not grouped", "The four enrollment status radios have no fieldset or legend.", "Wraps them in a fieldset with the legend \"Enrollment status\"."),
  d("underline", "underline-non-link", "LegacyAidPage", "markup", "minor",
    "\"will not\" is underlined", "\"Incomplete applications will not be processed\" underlines \"will not\" for emphasis.", "Uses bold instead."),
  d("fafsa-generic", "link-generic", "LegacyAidPage", "markup", "minor",
    "\"click here\" link", "The FAFSA reminder ends in a link reading \"click here\".", "The link reads \"How to file the FAFSA or CADAA\"."),
  d("tuition-document", "link-document", "LegacyAidPage", "markup", "minor",
    "Tuition schedule PDF link has no file info", "The \"Tuition schedule\" link opens a PDF with no type or size shown.", "Adds \"(PDF, 2 KB)\"."),
  d("privacy-new-window", "link-new-window", "LegacyAidPage", "markup", "minor",
    "Privacy notice opens a new window silently", "The privacy notice link opens a new window without saying so.", "Adds \"(opens in a new tab)\"."),
  d("section-headings", "heading-possible", "LegacyForm", "markup", "moderate",
    "Form sections use bold text, not headings", "\"STUDENT INFORMATION\", \"ENROLLMENT\" and the other section titles are bold table cells.", "Section titles are <h2>."),
  d("title-heading-skip", "heading-skipped", "LegacyAidPage", "markup", "moderate",
    "Form title is an <h3>", "The only real heading on the form is an <h3>; there is no <h1> or <h2> above it.", "The form title is the page <h1>."),
  d("household-caption", "table-no-caption", "LegacyHousehold", "markup", "minor",
    "Household table has no caption", "The household members table has no caption or name.", "Adds the caption \"Other members of your household\"."),
  d("justified", "text-justified", "LegacyAidPage", "markup", "minor",
    "Instructions are justified", "The instruction paragraphs use align=\"justify\"-style inline styles.", "Left-aligns the text."),
  d("banner-title", "img-title-attr", "LegacyBanner", "markup", "minor",
    "Banner has title=\"banner\"", "The banner image has a title attribute left from the template (\"banner\").", "Removes the title attribute."),
  d("spacer-alt", "alt-suspicious", "LegacyNav", "markup", "minor",
    "Spacer images have alt=\"spacer\"", "Transparent spacer GIFs in the menu have alt=\"spacer\".", "Spacers get alt=\"\"."),
  d("nav-duplicate", "link-nearby-duplicate", "LegacyNav", "markup", "minor",
    "Two adjacent \"Home\" links go to different pages", "The menu's first two links both read \"Home\"; one goes to the university home page, the other to Financial Aid.", "Links read \"RSU home\" and \"Financial Aid home\"."),
  d("nav-title", "title-redundant", "LegacyNav", "markup", "minor",
    "Menu links repeat their text as a title", "Each menu link has a title attribute identical to its text.", "Removes the title attributes."),
  d("nav-rollover", "event-handler-device", "LegacyNav", "behavior", "minor",
    "Menu highlight uses onmouseover only", "Menu links highlight through inline onmouseover/onmouseout handlers; keyboard focus gets nothing.", "Removes the handlers; CSS :hover and :focus highlight the link."),

  // ---------- Manual ----------
  d("banner-text-image", "text-in-image", "LegacyBanner", "markup", "moderate",
    "Banner text is an image", "The office name and \"Online Services\" are pixels in a banner graphic, so they don't scale or reflow.", "Renders the banner as styled HTML text."),
  d("intro-contrast", "contrast-text-low", "LegacyAidPage", "markup", "serious",
    "Gray instructions on gray", "Instructions are #999999 on #f0f0f0, about 2.5:1.", "Uses #333333 (about 11:1)."),
  d("print-mouse", "kbd-div-button", "LegacyAidPage", "behavior", "serious",
    "\"Print this form\" works only with a mouse", "The print link is an <a> with no href and a click handler, so it can't be focused or activated from the keyboard.", "Uses a <button>."),
  d("required-color", "color-only-required", "LegacyForm", "markup", "serious",
    "Required fields are marked only in red", "Required prompts are red text; the note says \"Items in red are required\".", "Adds \"(required)\" to prompts and the required attribute."),
  d("tabindex", "focus-positive-tabindex", "LegacyForm", "markup", "serious",
    "Positive tabindex values scramble the tab order", "Fields carry tabindex values from 1 to 30 left over from an older column layout, so Tab jumps around the form.", "Removes tabindex; the order follows the page."),
  d("timeout", "form-timeout-no-warning", "LegacySession", "behavior", "serious",
    "Session ends after 5 minutes with no warning", "Five minutes after the page loads, the form is replaced by \"Your session has timed out\" and everything entered is lost. The time limit is never mentioned.", "States the limit up front and shows a warning at 4 minutes with an \"Extend my session\" button."),
  d("aid-ungrouped", "form-ungrouped-controls", "LegacyForm", "markup", "moderate",
    "Aid type checkboxes are not grouped", "The three \"aid requested\" checkboxes are loose in table cells with no group or question.", "Wraps them in a fieldset with the legend \"Aid requested\"."),
  d("errors-vague", "form-vague-errors", "LegacyErrors", "behavior", "moderate",
    "One vague error for everything", "Any problem shows \"ERROR: Invalid input. Please check the form and try again.\"", "Lists each problem by field."),
  d("errors-not-announced", "sr-errors-not-announced", "LegacyErrors", "behavior", "serious",
    "Error message is not announced", "The error text appears at the top of the form without focus moving or any announcement.", "The error box has role=\"alert\" and receives focus."),
  d("marquee", "motion-animated-announcement", "LegacyAidPage", "css", "moderate",
    "Deadline notice scrolls like a marquee", "\"NEW! Priority deadline extended\" scrolls sideways continuously with no way to stop it.", "Shows the notice as static text."),
  d("reflow", "reflow-horizontal-scroll", "LegacyAidPage", "css", "serious",
    "Page is fixed at 780px", "The page table is 780px wide, so at 200% zoom or on a phone it scrolls sideways.", "Uses a fluid width."),
  d("focus-outline", "focus-indicator-missing", "LegacyAidPage", "css", "serious",
    "Focus outlines removed", "The legacy stylesheet sets outline: 0 on links and inputs.", "Restores a visible focus outline."),
  d("input-contrast", "contrast-ui-low", "LegacyForm", "css", "moderate",
    "Input borders are barely visible", "Text boxes have a 1px #dddddd border on white (about 1.4:1).", "Borders are #767676 (4.5:1)."),
  d("confirm-focus", "focus-lost-on-update", "LegacyConfirmation", "behavior", "moderate",
    "Confirmation replaces the form and loses focus", "After submitting, the form is replaced by the confirmation and focus is lost.", "Focus moves to the confirmation heading."),
  d("nav-arrows", "sr-decorative-announced", "LegacyNav", "markup", "minor",
    "Menu arrow bullets are read aloud", "Each menu item starts with an arrow image with alt=\"arrow\", so every link is announced as \"arrow\" first.", "Arrow bullets get alt=\"\"."),
];
