import type { ScenarioDef } from "./types";

const article = (slug: string) => `/news/${slug}`;

// RSU News (magazine CMS). Article links come from newsContent `links`; the two link scenarios list only
// the articles whose links carry that defect.
export const newsScenarios: ScenarioDef[] = [
  // ---------- /news (front) ----------
  {
    id: "news-front-lead-alt-long-001",
    rule: "alt-long",
    title: "Top story photo alt repeats the caption and summary",
    description: "The front-page photo's alt text is the image description plus the full caption, the story summary and a photo credit, well over 300 characters.",
    fixDescription: "Uses a short description of the photo.",
    pages: ["/news"],
    component: "NewsFront",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "news-front-card-alt-001",
    rule: "img-missing-alt",
    title: "Story card photos have no alt attribute",
    description: "Secondary and \"Latest stories\" card photos are rendered without an alt attribute.",
    fixDescription: "Marks the photos decorative (alt=\"\"); each card's headline names the story.",
    pages: ["/news"],
    component: "NewsFront",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "news-front-readmore-001",
    rule: "link-generic",
    title: "Story cards end in identical \"Read more\" links",
    description: "Every card has a \"Read more\" link, so a links list shows eight identical links.",
    fixDescription: "Adds the story headline to each link as visually hidden text.",
    pages: ["/news"],
    component: "NewsFront",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "news-front-kicker-contrast-001",
    rule: "contrast-text-low",
    title: "Section kickers are gold on white",
    description: "The small uppercase section labels on the front page use the brand gold (#c9a227) on white, about 2.3:1.",
    fixDescription: "Uses #b8543a, just above the 4.5:1 minimum.",
    pages: ["/news"],
    component: "NewsFront",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "news-front-mostread-heading-001",
    rule: "heading-skipped",
    title: "\"Most read\" heading jumps to h4",
    description: "The sidebar's \"Most read\" box uses an <h4> after <h2> section headings, skipping <h3>.",
    fixDescription: "Makes it an <h2> like the other front-page sections.",
    pages: ["/news"],
    component: "NewsFront",
    mechanism: "markup",
    severity: "moderate",
  },

  // ---------- /news/archive ----------
  {
    id: "news-archive-select-label-001",
    rule: "select-missing-label",
    title: "Section filter has no label",
    description: "The \"Section\" text next to the archive filter is a plain <span>, so the <select> has no accessible name.",
    fixDescription: "Turns the text into a <label> for the select.",
    pages: ["/news/archive"],
    component: "NewsArchive",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "news-archive-focus-001",
    rule: "focus-lost-on-update",
    title: "Focus is lost after changing pages",
    description: "After Next or a page number is activated the list is replaced but focus stays on the button. On the last page Next becomes disabled and focus falls back to the page body.",
    fixDescription: "Moves focus to the results heading after every page change.",
    pages: ["/news/archive"],
    component: "NewsArchive",
    mechanism: "behavior",
    severity: "serious",
  },
  {
    id: "news-archive-status-001",
    rule: "sr-status-not-announced",
    title: "\"Showing 6–10 of 15\" is not announced",
    description: "The result range updates silently when the page or section changes.",
    fixDescription: "Puts the range in a role=\"status\" live region.",
    pages: ["/news/archive"],
    component: "NewsArchive",
    mechanism: "behavior",
    severity: "moderate",
  },
  {
    id: "news-archive-meta-small-001",
    rule: "text-small",
    title: "Dates and bylines are 10px",
    description: "Archive rows set their date and byline at 10px.",
    fixDescription: "Uses 0.9rem (about 14px).",
    pages: ["/news/archive"],
    component: "NewsArchive",
    mechanism: "css",
    severity: "minor",
  },

  // ---------- /news/search ----------
  {
    id: "news-search-query-placeholder-001",
    rule: "placeholder-as-label",
    title: "News search uses a placeholder as its label",
    description: "The keyword box has only placeholder text, which disappears on typing and is low contrast.",
    fixDescription: "Adds a visible <label>.",
    pages: ["/news/search"],
    component: "NewsSearch",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "news-search-submit-empty-001",
    rule: "button-empty",
    title: "Search button is an unlabeled icon",
    description: "The magnifier submit button has no text, so it is announced as just \"button\".",
    fixDescription: "Adds visually hidden \"Search\" text.",
    pages: ["/news/search"],
    component: "NewsSearch",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "news-search-sort-label-001",
    rule: "label-for-mismatch",
    title: "\"Sort by\" label points at a missing id",
    description: "The label's for=\"sort\" does not match the select's id (\"news-sort\"), so the select is unnamed.",
    fixDescription: "Points the label at the select.",
    pages: ["/news/search"],
    component: "NewsSearch",
    mechanism: "markup",
    severity: "serious",
  },
  {
    id: "news-search-results-live-001",
    rule: "sr-results-no-live-region",
    title: "Result count is not announced",
    description: "After a search, \"N stories found\" appears silently; screen reader users don't know the search ran.",
    fixDescription: "Wraps the count in a role=\"status\" live region.",
    pages: ["/news/search"],
    component: "NewsSearch",
    mechanism: "behavior",
    severity: "moderate",
  },

  // ---------- /news/category/:slug ----------
  {
    id: "news-category-img-alt-001",
    rule: "alt-suspicious",
    title: "Section front photos use file names as alt",
    description: "Story photos on section fronts have alt text like \"news-madrone-hall-opens_web.jpg\".",
    fixDescription: "Marks the photos decorative (alt=\"\"); the headlines carry the meaning.",
    pages: ["/news/category/:slug"],
    component: "NewsCategory",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "news-category-readmore-001",
    rule: "link-generic",
    title: "\"Read more »\" links on section fronts",
    description: "Every story on a section front ends in an identical \"Read more »\" link.",
    fixDescription: "Uses \"Read the full story\" plus the headline as visually hidden text.",
    pages: ["/news/category/:slug"],
    component: "NewsCategory",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "news-category-intro-justified-001",
    rule: "text-justified",
    title: "Section introduction is justified",
    description: "The section introduction uses text-align: justify, leaving rivers of space in narrow columns.",
    fixDescription: "Left-aligns the introduction.",
    pages: ["/news/category/:slug"],
    component: "NewsCategory",
    mechanism: "css",
    severity: "minor",
  },

  // ---------- /news/:slug (ArticlePage) ----------
  {
    id: "news-article-lead-alt-001",
    rule: "alt-redundant",
    title: "Lead photo alt repeats its caption",
    description: "Article lead photos use the caption as alt text, so screen readers hear the same sentence twice.",
    fixDescription: "Uses a short description of the photo that complements the caption.",
    pages: ["/news/:slug"],
    component: "ArticlePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "news-article-byline-contrast-001",
    rule: "contrast-text-low",
    title: "Byline and date are light gray",
    description: "The byline, date and read time are #9a9a92 on white (about 2.8:1).",
    fixDescription: "Uses #767676, just above the 4.5:1 minimum.",
    pages: ["/news/:slug"],
    component: "ArticlePage",
    mechanism: "css",
    severity: "serious",
  },
  {
    id: "news-article-share-empty-001",
    rule: "link-empty",
    title: "Share links are icons with no text",
    description: "The PhotoPine, ReelWave, WorkCircle and email share links contain only decorative SVG icons.",
    fixDescription: "Adds visually hidden text such as \"Share on PhotoPine\".",
    pages: ["/news/:slug"],
    component: "ArticlePage",
    mechanism: "markup",
    severity: "critical",
  },
  {
    id: "news-article-subhead-001",
    rule: "heading-possible",
    title: "Story subheads are bold paragraphs",
    description: "Subheads pasted into the CMS body are bold <p> elements, so the article has no heading structure below the headline.",
    fixDescription: "Renders subheads as <h2>.",
    pages: ["/news/:slug"],
    component: "ArticlePage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "news-article-related-redundant-001",
    rule: "link-redundant",
    title: "Related story photo and headline are separate links",
    description: "Each related story links its photo (alt = headline) and its headline to the same URL, so every story is announced twice.",
    fixDescription: "Unlinks the photo and marks it decorative.",
    pages: ["/news/:slug"],
    component: "ArticlePage",
    mechanism: "markup",
    severity: "minor",
  },
  {
    id: "news-article-link-generic-001",
    rule: "link-generic",
    title: "\"Read more\" and \"Click here\" in More information",
    description: "The article's More information box uses the CMS link labels \"Read more\", \"Learn more\" or \"Click here\".",
    fixDescription: "Uses the destination page's title as the link text.",
    pages: [
      "engineering-robotics-lab-opens", "nursing-simulation-center-accreditation", "first-gen-scholars-expands",
      "library-digitizes-logging-archives", "wildfire-smoke-sensor-network", "mens-basketball-season-preview",
      "sleep-study-later-classes", "alum-california-teacher-of-year", "madrone-hall-opens", "green-chemistry-grant",
    ].map(article),
    component: "ArticlePage",
    mechanism: "markup",
    severity: "moderate",
  },
  {
    id: "news-article-link-pdf-001",
    rule: "link-document",
    title: "PDF links give no file size",
    description: "More information links end in \"(PDF)\" with no file size, and nothing warns that the file downloads.",
    fixDescription: "States the file type and size, e.g. \"(PDF, 2 KB)\".",
    pages: ["nursing-simulation-center-accreditation", "first-gen-scholars-expands", "library-digitizes-logging-archives", "mens-basketball-season-preview", "madrone-hall-opens"].map(article),
    component: "ArticlePage",
    mechanism: "markup",
    severity: "minor",
  },
];
