import type { ScenarioDef } from "./types";

// Every PortalPage-template route (registration is the plan 07 terrible SPA and has its own defects).
const PORTAL_PAGES = ["", "/schedule", "/grades", "/degree-progress", "/account", "/holds", "/todo", "/messages", "/profile"].map((p) => `/portal${p}`);

const s = (def: Omit<ScenarioDef, "pages"> & { pages?: string[] }, page: string): ScenarioDef => ({ pages: [page], ...def });

export const portalScenarios: ScenarioDef[] = [
  // ---------- PortalPage template ----------
  {
    id: "portal-template-print-empty-001",
    rule: "button-empty",
    title: "Page toolbar Print button has no name",
    description: "The printer icon button in every RedwoodConnect page header has no text or label.",
    fixDescription: "Adds a visually hidden \"Print this page\" label.",
    pages: PORTAL_PAGES,
    component: "PortalPage",
    mechanism: "markup",
    severity: "critical",
  },

  // ---------- /portal (dashboard, tier M) ----------
  s({
    id: "portal-dash-alert-live-001",
    rule: "aria-invalid-value",
    title: "Holds banner uses aria-live=\"yes\"",
    description: "The registration holds banner sets aria-live=\"yes\", which is not a valid value.",
    fixDescription: "Uses role=\"status\" (aria-live=\"polite\").",
    component: "HoldsBanner",
    mechanism: "markup",
    severity: "serious",
  }, "/portal"),
  s({
    id: "portal-dash-widget-heading-001",
    rule: "heading-possible",
    title: "Widget titles are styled text, not headings",
    description: "Dashboard widget titles (My Classes Today, Account Summary, To-Do, Messages) are bold paragraphs, so the page has no structure below the <h1>.",
    fixDescription: "Widget titles become <h2> headings.",
    component: "DashboardWidget",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal"),
  s({
    id: "portal-dash-asof-contrast-001",
    rule: "contrast-text-low",
    title: "Widget footnotes are pale gray",
    description: "\"As of\" and \"due\" footnotes in the widgets are #a3adb8 on white (about 2.3:1).",
    fixDescription: "Uses #5b6673 (about 5.9:1).",
    component: "DashboardWidget",
    mechanism: "css",
    severity: "serious",
  }, "/portal"),
  s({
    id: "portal-dash-viewall-001",
    rule: "link-generic",
    title: "Every widget ends in \"View all\"",
    description: "Four widgets each end with a link reading only \"View all\".",
    fixDescription: "Each link names its destination, e.g. \"View all messages\".",
    component: "DashboardWidget",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal"),
  s({
    id: "portal-dash-unread-color-001",
    rule: "color-only-info",
    title: "Unread messages are marked by a blue dot only",
    description: "Unread messages in the Messages widget are shown only by a small blue dot.",
    fixDescription: "Adds a visible \"New\" badge.",
    component: "DashboardWidget",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal"),

  // ---------- /portal/schedule (tier M) ----------
  s({
    id: "portal-sched-caption-001",
    rule: "table-no-caption",
    title: "Class list table has no caption",
    description: "The class list data grid has no <caption>.",
    fixDescription: "Adds a caption with the term.",
    component: "ScheduleGrid",
    mechanism: "markup",
    severity: "minor",
  }, "/portal/schedule"),
  s({
    id: "portal-sched-week-clip-001",
    rule: "reflow-overflow-200",
    title: "Weekly calendar is fixed-width and clipped",
    description: "The week view is a fixed 56rem wide inside a container with overflow hidden, so Thursday and Friday are cut off at 200% zoom or on small screens.",
    fixDescription: "The week view scrolls inside its own container.",
    component: "WeekView",
    mechanism: "css",
    severity: "serious",
  }, "/portal/schedule"),
  s({
    id: "portal-sched-map-window-001",
    rule: "link-new-window",
    title: "Building map links open new tabs without warning",
    description: "Each building name opens the campus map in a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\".",
    component: "ScheduleGrid",
    mechanism: "markup",
    severity: "minor",
  }, "/portal/schedule"),

  // ---------- /portal/grades (tier M) ----------
  s({
    id: "portal-grades-heading-skip-001",
    rule: "heading-skipped",
    title: "Term headings skip from h2 to h4",
    description: "Each term's heading is an <h4> under the \"Grade History\" <h2>.",
    fixDescription: "Term headings become <h3>.",
    component: "GradesPage",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/grades"),
  s({
    id: "portal-grades-duplicate-id-001",
    rule: "duplicate-id",
    title: "Every term table reuses the same ids",
    description: "Each term table copies the same header ids (grade-course, grade-title...) and the cells point at them with headers, so ids repeat four times.",
    fixDescription: "Prefixes each table's ids with the term.",
    // The repeated ids are referenced by headers, not ARIA, so axe reports the cross-table headers instead.
    detectedBy: { axe: ["td-headers-attr"] },
    component: "GradesPage",
    mechanism: "markup",
    severity: "serious",
  }, "/portal/grades"),
  s({
    id: "portal-grades-footnote-small-001",
    rule: "text-small",
    title: "GPA footnote is 10px",
    description: "The note about which grades count toward GPA is 10px text.",
    fixDescription: "Uses 0.875rem text.",
    component: "GradesPage",
    mechanism: "css",
    severity: "minor",
  }, "/portal/grades"),
  s({
    id: "portal-grades-calendar-pdf-001",
    rule: "link-document",
    title: "Academic calendar link doesn't say it's a PDF",
    description: "\"Academic calendar\" downloads a PDF with no file type or size.",
    fixDescription: "Adds the file type and size.",
    component: "GradesPage",
    mechanism: "markup",
    severity: "minor",
  }, "/portal/grades"),

  // ---------- /portal/degree-progress (tier H) ----------
  s({
    id: "portal-audit-progress-name-001",
    rule: "sr-visual-only-state",
    title: "Degree progress bar is a bare div",
    description: "Overall progress is a colored div: the percent complete is conveyed only by its width, with no role, name or value.",
    fixDescription: "Uses role=\"progressbar\" with a name and value, and shows the percentage as text.",
    component: "AuditSummary",
    mechanism: "markup",
    severity: "serious",
  }, "/portal/degree-progress"),
  s({
    id: "portal-audit-progress-contrast-001",
    rule: "contrast-ui-low",
    title: "Progress bar fill barely differs from its track",
    description: "The progress fill is #b9d3ee on a #e6ebf1 track (about 1.3:1).",
    fixDescription: "Uses #0b5cad for the fill and a darker track border.",
    component: "AuditSummary",
    mechanism: "css",
    severity: "moderate",
  }, "/portal/degree-progress"),
  s({
    id: "portal-audit-summary-layout-001",
    rule: "table-layout",
    title: "Audit summary uses a layout table",
    description: "The student summary (program, catalog year, advisor, credits) is laid out with a <table> that has no headers and no role.",
    fixDescription: "Uses a description list.",
    component: "AuditSummary",
    mechanism: "markup",
    severity: "minor",
  }, "/portal/degree-progress"),
  s({
    id: "portal-audit-status-color-001",
    rule: "color-only-info",
    title: "Requirement status is a colored dot",
    description: "Each course's status (complete, in progress, not started) is shown only by a green, amber or gray dot.",
    fixDescription: "Adds the status as text next to the dot.",
    component: "RequirementGroup",
    mechanism: "markup",
    severity: "serious",
  }, "/portal/degree-progress"),
  s({
    id: "portal-audit-group-heading-001",
    rule: "heading-possible",
    title: "Requirement group names are bold text",
    description: "Requirement group names (Lower-Division Core, Mathematics...) are bold paragraphs, not headings.",
    fixDescription: "Group names become <h3> headings.",
    component: "RequirementGroup",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/degree-progress"),
  s({
    id: "portal-audit-notes-list-001",
    rule: "list-structure",
    title: "Audit notes are <li> elements in a <div>",
    description: "The advisor notes are <li> elements inside a <div>, with no <ul>.",
    fixDescription: "Wraps the items in a <ul>.",
    component: "AuditNotes",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/degree-progress"),
  s({
    id: "portal-audit-whatif-generic-001",
    rule: "link-generic",
    title: "\"Click here\" link to explore other majors",
    description: "The what-if prompt ends in a link reading \"Click here\".",
    fixDescription: "The link names its destination.",
    component: "AuditNotes",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/degree-progress"),
  s({
    id: "portal-audit-group-spacing-001",
    rule: "text-spacing-breaks",
    title: "Group headers clip when text spacing is increased",
    description: "Requirement group header bars have a fixed 2.25rem height with overflow hidden, so user text-spacing overrides (or wrapping on narrow screens) clip the text.",
    fixDescription: "Uses padding and min-height instead of a fixed height.",
    component: "RequirementGroup",
    mechanism: "css",
    severity: "moderate",
  }, "/portal/degree-progress"),
  s({
    id: "portal-audit-credits-underline-001",
    rule: "underline-non-link",
    title: "Credit totals are underlined like links",
    description: "Group credit totals (\"12 of 17 credits\") are underlined to show they are totals, so they look like links.",
    fixDescription: "Removes the underline and uses bold.",
    component: "RequirementGroup",
    mechanism: "css",
    severity: "minor",
  }, "/portal/degree-progress"),

  // ---------- /portal/account (tier M) ----------
  s({
    id: "portal-acct-credit-color-001",
    rule: "color-only-info",
    title: "Payments and aid are shown only in green",
    description: "Ledger credits (payments and aid) are shown as positive numbers in green, the same format as charges except for color.",
    fixDescription: "Credits show a minus sign and a \"Credit\" label.",
    component: "Ledger",
    mechanism: "markup",
    severity: "serious",
  }, "/portal/account"),
  s({
    id: "portal-acct-caption-001",
    rule: "table-no-caption",
    title: "Account activity table has no caption",
    description: "The account activity data grid has no <caption>.",
    fixDescription: "Adds a caption.",
    component: "Ledger",
    mechanism: "markup",
    severity: "minor",
  }, "/portal/account"),
  s({
    id: "portal-acct-epay-window-001",
    rule: "link-new-window",
    title: "Payment link opens a new window without warning",
    description: "\"Make a payment\" opens RedwoodConnect ePay in a new window with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\".",
    component: "AccountSummary",
    mechanism: "markup",
    severity: "minor",
  }, "/portal/account"),
  s({
    id: "portal-acct-tuition-pdf-001",
    rule: "link-document",
    title: "Tuition schedule link doesn't say it's a PDF",
    description: "\"Tuition and fee schedule\" downloads a PDF with no file type or size.",
    fixDescription: "Adds the file type and size.",
    component: "AccountSummary",
    mechanism: "markup",
    severity: "minor",
  }, "/portal/account"),

  // ---------- /portal/holds (tier M) ----------
  s({
    id: "portal-holds-heading-empty-001",
    rule: "heading-empty",
    title: "Empty heading above the holds grid",
    description: "The vendor's notice slot renders an empty <h2> when no office notice is configured.",
    fixDescription: "Removes the empty heading.",
    component: "HoldsPage",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/holds"),
  s({
    id: "portal-holds-blocks-color-001",
    rule: "color-only-info",
    title: "\"Blocks registration\" is a red icon only",
    description: "Whether a hold blocks registration is shown only by a red stop icon with no text.",
    fixDescription: "Lists what each hold blocks as text.",
    component: "HoldsPage",
    mechanism: "markup",
    severity: "serious",
  }, "/portal/holds"),
  s({
    id: "portal-holds-resolve-generic-001",
    rule: "link-generic",
    title: "Hold actions all read \"More info\"",
    description: "Each hold's action link reads only \"More info\".",
    fixDescription: "The link names the hold and what to do.",
    component: "HoldsPage",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/holds"),

  // ---------- /portal/todo (tier L) ----------
  s({
    id: "portal-todo-due-color-001",
    rule: "color-only-info",
    title: "Items due soon are marked only in red",
    description: "Open items due within two weeks have a red due date and nothing else to set them apart.",
    fixDescription: "Adds a visible \"Due soon\" label.",
    component: "TodoPage",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/todo"),

  // ---------- /portal/messages (tier H) ----------
  s({
    id: "portal-msg-row-click-001",
    rule: "kbd-div-button",
    title: "Inbox rows open only on mouse click",
    description: "Inbox rows are clickable table rows with no link or button, so keyboard users can't open a message.",
    fixDescription: "The subject becomes a link to the message.",
    component: "Inbox",
    mechanism: "behavior",
    severity: "critical",
  }, "/portal/messages"),
  s({
    id: "portal-msg-unread-bold-001",
    rule: "sr-visual-only-state",
    title: "Unread state is shown only by bold text",
    description: "Unread messages are bold; screen readers get no indication that a message is unread.",
    fixDescription: "Adds a visible \"Unread\" label.",
    component: "Inbox",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/messages"),
  s({
    id: "portal-msg-checkbox-label-001",
    rule: "input-missing-label",
    title: "Row select checkboxes have no label",
    description: "The checkbox at the start of each inbox row has no label.",
    fixDescription: "Each checkbox is labeled with the message subject.",
    component: "Inbox",
    mechanism: "markup",
    severity: "critical",
  }, "/portal/messages"),
  s({
    id: "portal-msg-search-placeholder-001",
    rule: "placeholder-as-label",
    title: "Message search uses a placeholder as its label",
    description: "The inbox search box has only placeholder text, which disappears as soon as you type.",
    fixDescription: "Adds a visible label.",
    component: "Inbox",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/messages"),
  s({
    id: "portal-msg-date-contrast-001",
    rule: "contrast-text-low",
    title: "Inbox dates are pale gray",
    description: "The date column is #a3adb8 on white (about 2.3:1).",
    fixDescription: "Uses #5b6673 (about 5.9:1).",
    component: "Inbox",
    mechanism: "css",
    severity: "serious",
  }, "/portal/messages"),
  s({
    id: "portal-msg-subject-heading-001",
    rule: "heading-skipped",
    title: "Message subjects skip from h2 to h4",
    description: "Each message's subject is an <h4> directly under the \"Messages\" <h2>.",
    fixDescription: "Subjects become <h3>.",
    component: "MessageView",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/messages"),
  s({
    id: "portal-msg-click-here-001",
    rule: "link-generic",
    title: "Messages end in \"Click here\" links",
    description: "Action links at the end of messages read \"Click here\".",
    fixDescription: "The links name their destination.",
    component: "MessageView",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/messages"),
  s({
    id: "portal-msg-labeledby-001",
    rule: "aria-invalid-attr",
    title: "Reading pane uses the misspelled aria-labeledby",
    description: "The message reading pane sets aria-labeledby (one L), which is not an ARIA attribute, so the region has no name.",
    fixDescription: "Uses aria-labelledby.",
    component: "MessageView",
    mechanism: "markup",
    severity: "serious",
  }, "/portal/messages"),

  // ---------- /portal/profile (tier M) ----------
  s({
    id: "portal-profile-for-mismatch-001",
    rule: "label-for-mismatch",
    title: "Chosen name label points at the wrong id",
    description: "The \"Chosen first name\" label's for attribute points at an id that doesn't exist.",
    fixDescription: "The label's for matches the input id.",
    component: "ProfileForm",
    mechanism: "markup",
    severity: "critical",
  }, "/portal/profile"),
  s({
    id: "portal-profile-phone-placeholder-001",
    rule: "placeholder-as-label",
    title: "Mobile phone field uses a placeholder as its label",
    description: "The mobile phone field has only placeholder text as its label.",
    fixDescription: "Adds a visible label.",
    component: "ProfileForm",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/profile"),
  s({
    id: "portal-profile-pronouns-label-001",
    rule: "select-missing-label",
    title: "Pronouns select has no label",
    description: "The \"Pronouns\" text next to the select is a <span>, so the select has no name.",
    fixDescription: "Uses a <label>.",
    component: "ProfileForm",
    mechanism: "markup",
    severity: "critical",
  }, "/portal/profile"),
  s({
    id: "portal-profile-radios-fieldset-001",
    rule: "fieldset-missing",
    title: "Text alert radios are not grouped",
    description: "The Yes/No radios for emergency text alerts have no fieldset or legend, so \"Yes\" and \"No\" have no question.",
    fixDescription: "Groups them in a fieldset with a legend.",
    component: "ProfileForm",
    mechanism: "markup",
    severity: "moderate",
  }, "/portal/profile"),
  s({
    id: "portal-profile-required-color-001",
    rule: "color-only-required",
    title: "Required fields are marked by red labels only",
    description: "Required fields are indicated only by a red label color.",
    fixDescription: "Adds \"(required)\" to the label and the required attribute.",
    component: "ProfileForm",
    mechanism: "markup",
    severity: "serious",
  }, "/portal/profile"),
  s({
    id: "portal-profile-ferpa-pdf-001",
    rule: "link-document",
    title: "FERPA notice link doesn't say it's a PDF",
    description: "\"FERPA annual notice\" downloads a PDF with no file type or size.",
    fixDescription: "Adds the file type and size.",
    component: "ProfilePage",
    mechanism: "markup",
    severity: "minor",
  }, "/portal/profile"),
];
