import type { ScenarioDef } from "./types";

// /portal/registration: the Student Registration SPA, one of plan 07's six terrible pages (tier T).
// The PortalPage template's Print button (portal-template-print-empty-001, in portal.ts) also renders here.
const r = (def: Omit<ScenarioDef, "pages">): ScenarioDef => ({ pages: ["/portal/registration"], ...def });

export const registrationScenarios: ScenarioDef[] = [
  // ---------- Errors ----------
  r({
    id: "portal-reg-subject-label-001",
    rule: "select-missing-label",
    title: "Subject select has no label",
    description: "The \"Subject\" text above the class search select is a <span>, so the select has no accessible name.",
    fixDescription: "Uses a <label for>.",
    component: "ClassSearch", mechanism: "markup", severity: "critical",
  }),
  r({
    id: "portal-reg-crn-label-001",
    rule: "input-missing-label",
    title: "\"Add by CRN\" input has no label",
    description: "The quick-add CRN box shows \"Add by CRN\" as plain text that isn't associated with the input.",
    fixDescription: "Uses a <label for>.",
    component: "QuickAdd", mechanism: "markup", severity: "critical",
  }),
  r({
    id: "portal-reg-add-empty-001",
    rule: "button-empty",
    title: "\"Add to cart\" buttons are unnamed plus icons",
    description: "Each section's add button is a plus icon with no text, so every button is announced only as \"button\".",
    fixDescription: "Each button is named, e.g. \"Add CS 313-01 to cart\".",
    component: "SectionGrid", mechanism: "markup", severity: "critical",
  }),
  r({
    id: "portal-reg-details-controls-001",
    rule: "aria-broken-reference",
    title: "Details toggles point aria-controls at missing ids",
    description: "Each section's Details button has aria-controls=\"details-<CRN>\", an id left over from an older template; the details row is actually rg-sec-<CRN>-details.",
    fixDescription: "aria-controls references the details row's real id.",
    component: "SectionGrid", mechanism: "markup", severity: "serious",
  }),
  r({
    id: "portal-reg-grid-children-001",
    rule: "aria-required-children",
    title: "Section results use role=\"grid\" with no rows or cells",
    description: "Each course's sections are nested <div>s inside role=\"grid\" with no row, columnheader or gridcell roles, so the grid has none of its required children and the column headers mean nothing to a screen reader.",
    fixDescription: "Renders a data table with a caption and column headers.",
    component: "SectionGrid", mechanism: "markup", severity: "critical",
  }),
  r({
    id: "portal-reg-result-icon-alt-001",
    rule: "img-missing-alt",
    title: "Registration result icons have no alt text",
    description: "After Register, each class's status (registered, waitlisted, not registered) is a colored icon <img> with no alt attribute and no text.",
    fixDescription: "The icon gets alt=\"\" and the status is written out next to it.",
    component: "Results", mechanism: "markup", severity: "critical",
  }),
  r({
    id: "portal-reg-adv-hidden-focus-001",
    rule: "aria-hidden-focusable",
    title: "Collapsed search options are aria-hidden but still focusable",
    description: "\"More search options\" is collapsed with aria-hidden=\"true\" and a zero height, but its checkbox and select can still be reached with Tab.",
    fixDescription: "The collapsed panel uses the hidden attribute.",
    component: "ClassSearch", mechanism: "markup", severity: "serious",
  }),
  r({
    id: "portal-reg-meter-value-001",
    rule: "aria-invalid-value",
    title: "Credit meter's aria-valuenow is text",
    description: "The cart's credit progress bar sets aria-valuenow=\"12 credits\"; the value must be a number.",
    fixDescription: "Uses a numeric aria-valuenow with aria-valuetext \"12 of 18 credits\".",
    component: "CreditMeter", mechanism: "markup", severity: "serious",
  }),
  r({
    id: "portal-reg-adv-expandable-001",
    rule: "aria-invalid-attr",
    title: "Search options toggle uses aria-expandable",
    description: "The \"More search options\" button sets aria-expandable, which is not an ARIA attribute, so its state is never exposed.",
    fixDescription: "Uses aria-expanded and aria-controls.",
    component: "ClassSearch", mechanism: "markup", severity: "serious",
  }),

  // ---------- Alerts ----------
  r({
    id: "portal-reg-keyword-placeholder-001",
    rule: "placeholder-as-label",
    title: "Keyword search uses a placeholder as its label",
    description: "The keyword box is labeled only by placeholder text, which disappears as soon as you type.",
    fixDescription: "Adds a visible label.",
    component: "ClassSearch", mechanism: "markup", severity: "moderate",
  }),
  r({
    id: "portal-reg-remove-js-001",
    rule: "link-javascript",
    title: "Cart \"Remove\" is a href=\"#\" link",
    description: "Each cart item's Remove action is a link to \"#\" driven by a click handler, and every one reads just \"Remove\".",
    fixDescription: "Uses a button named with the class, e.g. \"Remove CS 313-01\".",
    component: "Cart", mechanism: "markup", severity: "moderate",
  }),
  r({
    id: "portal-reg-cart-heading-skip-001",
    rule: "heading-skipped",
    title: "Shopping cart heading jumps from h1 to h4",
    description: "The cart panel's heading is an <h4> directly after the page's <h1>.",
    fixDescription: "The cart heading is an <h2>.",
    component: "Cart", mechanism: "markup", severity: "moderate",
  }),
  r({
    id: "portal-reg-course-heading-001",
    rule: "heading-possible",
    title: "Course titles in results are bold text",
    description: "Each course in the search results (\"CS 313 · Software Engineering\") is a bold paragraph, so results can't be navigated by heading.",
    fixDescription: "Course titles are <h3> headings.",
    component: "ClassSearch", mechanism: "markup", severity: "moderate",
  }),
  r({
    id: "portal-reg-schedule-caption-001",
    rule: "table-no-caption",
    title: "Current schedule table has no caption",
    description: "The Current Schedule tab's table has no <caption>.",
    fixDescription: "Adds a caption naming the term.",
    component: "CurrentSchedule", mechanism: "markup", severity: "minor",
  }),
  r({
    id: "portal-reg-store-window-001",
    rule: "link-new-window",
    title: "Bookstore link opens a new tab without warning",
    description: "\"RSU Bookstore\" opens the textbook lookup in a new tab with no warning.",
    fixDescription: "Adds \"(opens in a new tab)\".",
    component: "RegistrationIntro", mechanism: "markup", severity: "minor",
  }),
  r({
    id: "portal-reg-calendar-pdf-001",
    rule: "link-document",
    title: "Academic calendar link doesn't say it's a PDF",
    description: "\"academic calendar\" downloads a PDF with no file type or size.",
    fixDescription: "Adds the file type and size.",
    component: "RegistrationIntro", mechanism: "markup", severity: "minor",
  }),
  r({
    id: "portal-reg-seats-note-small-001",
    rule: "text-small",
    title: "Seat and waitlist note is 10px",
    description: "The note explaining seat refreshes and the 24-hour waitlist claim window is 10px text.",
    fixDescription: "Uses 0.875rem text.",
    component: "ClassSearch", mechanism: "css", severity: "minor",
  }),

  // ---------- Manual ----------
  r({
    id: "portal-reg-term-dropdown-001",
    rule: "kbd-dropdown-inoperable",
    title: "Term picker works only with a mouse",
    description: "The term selector is a styled <div> that opens a list of clickable <div> options; it can't be focused or operated by keyboard and has no name.",
    fixDescription: "Uses a labeled native <select>.",
    component: "RegistrationIntro", mechanism: "behavior", severity: "critical",
  }),
  r({
    id: "portal-reg-tabs-keys-001",
    rule: "kbd-tabs-wrong-keys",
    title: "Find Classes / Current Schedule tabs ignore arrow keys",
    description: "The tabs have tab roles, but only the selected tab is in the Tab order and Arrow, Home and End keys do nothing, so keyboard users can't reach Current Schedule.",
    fixDescription: "Arrow keys, Home and End move between tabs (APG tabs pattern).",
    component: "RegistrationTabs", mechanism: "behavior", severity: "serious",
  }),
  r({
    id: "portal-reg-drag-001",
    rule: "kbd-drag-no-alternative",
    title: "Cart priority can only be changed by drag and drop",
    description: "Cart items are reordered by dragging; there is no keyboard or single-pointer alternative.",
    fixDescription: "Adds named Move up / Move down buttons to each item (dragging still works).",
    component: "Cart", mechanism: "behavior", severity: "serious",
  }),
  r({
    id: "portal-reg-cart-focus-001",
    rule: "focus-lost-on-update",
    title: "Focus is lost after adding to or removing from the cart",
    description: "Adding a section replaces its Add button with \"In cart\", and removing an item deletes its Remove link; either way focus drops to the top of the page.",
    fixDescription: "Focus moves to the updated cart heading.",
    component: "Cart", mechanism: "behavior", severity: "serious",
  }),
  r({
    id: "portal-reg-conflict-color-001",
    rule: "color-only-error",
    title: "Time conflicts are shown only by a red border",
    description: "A cart item that overlaps an enrolled class or another cart item gets a red left border and red times, with no text saying what conflicts.",
    fixDescription: "Adds a warning icon and \"Time conflict with …\" text.",
    component: "Cart", mechanism: "markup", severity: "serious",
  }),
  r({
    id: "portal-reg-conflict-announce-001",
    rule: "sr-errors-not-announced",
    title: "Time conflict errors are never announced",
    description: "When a conflict appears in the cart, nothing is sent to assistive technology.",
    fixDescription: "The conflict message is in a role=\"alert\" region.",
    component: "Cart", mechanism: "markup", severity: "serious",
  }),
  r({
    id: "portal-reg-processing-trap-001",
    rule: "kbd-focus-trap-bad",
    title: "\"Processing…\" overlay doesn't hold focus",
    description: "The processing overlay is a styled <div>: focus stays behind it and Tab keeps moving through the page, including the Register button.",
    fixDescription: "Uses a modal <dialog> that contains focus while processing.",
    component: "Processing", mechanism: "behavior", severity: "serious",
  }),
  r({
    id: "portal-reg-processing-restore-001",
    rule: "focus-not-restored",
    title: "Focus is dropped when registration finishes",
    description: "When processing ends the overlay disappears and focus is blurred to the document, so keyboard and screen reader users don't reach the results.",
    fixDescription: "Focus moves to the Registration Results heading.",
    component: "Processing", mechanism: "behavior", severity: "serious",
  }),
  r({
    id: "portal-reg-spinner-motion-001",
    rule: "motion-ignores-reduced-motion",
    title: "Processing spinner ignores reduced motion",
    description: "The processing spinner keeps spinning when the user asks for reduced motion.",
    fixDescription: "The spinner stops under prefers-reduced-motion.",
    component: "Processing", mechanism: "css", severity: "minor",
  }),
  r({
    id: "portal-reg-results-live-001",
    rule: "sr-results-no-live-region",
    title: "Search result counts aren't announced",
    description: "\"Searching…\" and the updated result count change silently after each search.",
    fixDescription: "The count is a role=\"status\" live region.",
    component: "ClassSearch", mechanism: "markup", severity: "moderate",
  }),
  r({
    id: "portal-reg-toast-001",
    rule: "sr-status-not-announced",
    title: "\"Added to cart\" message vanishes unannounced",
    description: "The cart confirmation toast is not a live region and disappears after 3 seconds.",
    fixDescription: "A persistent role=\"status\" message with a Dismiss button.",
    component: "Toast", mechanism: "behavior", severity: "moderate",
  }),
  r({
    id: "portal-reg-seats-color-001",
    rule: "color-only-info",
    title: "Seat availability is a colored square",
    description: "Each section's availability (open, few seats left, full) is shown only by a green, amber or red square.",
    fixDescription: "Adds the seat count or waitlist as text.",
    component: "SectionGrid", mechanism: "markup", severity: "serious",
  }),
  r({
    id: "portal-reg-footnote-contrast-001",
    rule: "contrast-text-low",
    title: "Credit limit note is pale gray",
    description: "The note about the credit maximum under the cart is #a3adb8 on white (about 2.3:1).",
    fixDescription: "Uses #6c7684, just above the 4.5:1 minimum.",
    component: "Cart", mechanism: "css", severity: "serious",
  }),
  r({
    id: "portal-reg-crn-vague-001",
    rule: "form-vague-errors",
    title: "CRN errors just say \"Invalid entry.\"",
    description: "Any unknown or malformed CRN produces \"Invalid entry.\" with no hint of what went wrong or how to fix it, and the message isn't tied to the input.",
    fixDescription: "Says what is wrong (format or no such section this term), marks the input aria-invalid and links the message with aria-describedby.",
    component: "QuickAdd", mechanism: "behavior", severity: "moderate",
  }),
  r({
    id: "portal-reg-cart-focus-ring-001",
    rule: "focus-indicator-missing",
    title: "Cart controls have no focus outline",
    description: "The cart's stylesheet sets outline: none on its buttons, links and inputs, so keyboard focus is invisible there.",
    fixDescription: "Restores a 3px focus outline.",
    component: "Cart", mechanism: "css", severity: "serious",
  }),
  r({
    id: "portal-reg-layout-reflow-001",
    rule: "reflow-horizontal-scroll",
    title: "Registration layout needs horizontal scrolling at 200% zoom",
    description: "The cart and search columns sit in a layout with a 64rem minimum width, so at 200% zoom or on a phone the whole page scrolls sideways.",
    fixDescription: "The columns stack below 60rem.",
    component: "RegistrationLayout", mechanism: "css", severity: "serious",
  }),
];
