// Generates docs/SITE_MAP.md from src/routes/inventory.ts and the scenario registry, so the doc never
// drifts from the code. Run: npm run gen:sitemap (chained into `npm run build`).
import { writeFile } from "node:fs/promises";
import { registerHooks } from "node:module";

registerHooks({
  resolve(spec, ctx, next) {
    try { return next(spec, ctx); } catch (e) { if (spec.startsWith(".")) return next(`${spec}.ts`, ctx); throw e; }
  },
});
const { scenarios } = await import("../src/a11y/registry/index");
const { inventory } = await import("../src/routes/inventory");

// Same page-level (excludes chrome "*" scenarios) count as scripts/coverage.ts, so the two never disagree.
const university = inventory.filter((e) => e.section !== "lab" && e.section !== "portal").map((e) => e.path);
const expand = (page: string) =>
  page === "*" ? university : page.includes(":") ? inventory.filter((e) => e.pattern === page).map((e) => e.path) : [page];

const pageCount = new Map<string, number>();
for (const s of scenarios.values()) {
  if (s.pages.includes("*")) continue;
  for (const p of s.pages.flatMap(expand)) pageCount.set(p, (pageCount.get(p) ?? 0) + 1);
}

const sectionTitle: Record<string, string> = {
  home: "Home", about: "About", admissions: "Admissions", aid: "Financial Aid", academics: "Academics",
  faculty: "Faculty", students: "Student Affairs", library: "Library", news: "News", events: "Events",
  athletics: "Athletics", giving: "Giving", employees: "Employees (Intranet)", portal: "Student Portal",
  audience: "Audiences", utility: "Utility", lab: "Accessibility Lab",
};

const bySection = new Map<string, typeof inventory[number][]>();
for (const e of inventory) {
  const list = bySection.get(e.section) ?? [];
  list.push(e);
  bySection.set(e.section, list);
}

let out = `# Site Map\n\nGenerated by \`scripts/gen-sitemap-md.ts\` from \`src/routes/inventory.ts\`. Do not edit by hand; run \`npm run gen:sitemap\`.\n\n${inventory.length} routes. "Scenarios" is the page-level count only (excludes sitewide chrome defects).\n`;

for (const [section, entries] of bySection) {
  out += `\n## ${sectionTitle[section] ?? section}\n\n| Route | Tier | Scenarios |\n|---|---|---|\n`;
  for (const e of entries) {
    out += `| ${e.path} | ${e.tier} | ${pageCount.get(e.path) ?? 0} |\n`;
  }
}

await writeFile("docs/SITE_MAP.md", out);
console.log(`gen:sitemap: wrote docs/SITE_MAP.md (${inventory.length} routes)`);
