// Writes small one-page fake PDFs to public/documents/ (targets for "link to document" alerts).
// Hand-written PDF syntax, no dependencies. Run: npm run gen:docs
import { mkdirSync, writeFileSync } from "node:fs";

const OUT = new URL("../public/documents/", import.meta.url);

// [file, title, lines]; "# " marks a heading. ASCII only (standard Helvetica encoding).
const DOCS: [string, string, string[]][] = [
  ["tuition-schedule-2025-26.pdf", "2025-26 Tuition and Fee Schedule", [
    "Rates per semester, effective Fall 2025. Approved by the Board of Trustees, May 2025.",
    "# Undergraduate",
    "California resident, 6.1 or more units ........ $3,871.00",
    "California resident, 0 to 6.0 units ........... $2,246.00",
    "Nonresident tuition, per unit (added) ......... $396.00",
    "# Graduate",
    "California resident, 6.1 or more units ........ $4,531.00",
    "California resident, 0 to 6.0 units ........... $2,629.00",
    "# Mandatory campus fees (all students)",
    "Student Union fee ............................. $412.00",
    "Health services fee ........................... $157.00",
    "Instructionally related activities fee ........ $243.00",
    "Associated Students fee ....................... $118.00",
    "Student success fee ........................... $86.00",
    "Fees are subject to change without notice. Course materials and lab fees are listed in the",
    "Class Schedule. Questions: Student Financial Services, Founders Hall 120, (707) 555-0114.",
  ]],
  ["catalog-addendum-2025-26.pdf", "General Catalog 2025-2026 Addendum", [
    "This addendum updates the 2025-2026 General Catalog. It supersedes the printed catalog.",
    "# Changes to courses",
    "CS 304 Operating Systems: Prerequisite is now CS 201 only (CS 209 no longer required).",
    "MATH 119: Course retitled Statistics for Everyday Life (was Quantitative Reasoning).",
    "NURS 301: Clinical hours increased from 90 to 135; units unchanged.",
    "ENVS 301: New course, Wildfire and Forest Management (3 units).",
    "# Changes to programs",
    "B.S. Computer Science: CS 333 Accessible and Inclusive Software Design added as an",
    "upper-division core option beginning Fall 2026.",
    "M.B.A.: Capstone may be completed as a consulting project or a thesis.",
    "# Policy updates",
    "The deadline to withdraw without a W grade is now the end of the third week of instruction.",
    "Posted by the Office of the Registrar. Last revised August 12, 2025.",
  ]],
  ["parking-map.pdf", "Campus Parking Map and Permit Guide", [
    "Permits are required Monday through Friday, 7:00 a.m. to 10:00 p.m., in all campus lots.",
    "# Lots by permit type",
    "Lot A (Founders Hall) ............... Faculty/Staff (F), Visitor pay stations",
    "Lot B (Canopy Science Center) ...... General (G)",
    "Lot C (Owl Arena) ........ General (G), Event parking",
    "Lot D (Madrone Hall) ............... Residential (R) only",
    "Lot E (Corporation Yard) ........... Service vehicles, Carpool (CP)",
    "Structure 1 (Rowan Student Union) ........ General (G), Faculty/Staff (F) levels 3-4",
    "# Accessible parking",
    "Accessible spaces are in every lot. A state disabled placard plus any valid RSU permit",
    "is required. Van-accessible spaces: Lots A, B, and Structure 1 level 1.",
    "# Permit prices (per semester)",
    "General (G) $238.00 | Residential (R) $262.00 | Faculty/Staff (F) $300.00 | Motorcycle $60.00",
    "Parking & Transportation Services, Corporation Yard, (707) 555-0162.",
    "Note: this map is a text version. A graphical map is available at the Parking office.",
  ]],
  ["student-conduct-code.pdf", "Student Conduct Code", [
    "Executive Order SA-14. Revised July 2024.",
    "# Purpose",
    "Redwood State University is committed to a safe learning environment. This code describes",
    "the standards of conduct expected of students and the process for resolving alleged violations.",
    "# Prohibited conduct (summary)",
    "1. Academic dishonesty, including cheating, plagiarism, and unauthorized use of AI tools.",
    "2. Harassment, threats, or conduct that endangers the health or safety of any person.",
    "3. Theft of or damage to university or personal property.",
    "4. Unauthorized use of alcohol, cannabis, or other controlled substances on campus.",
    "5. Misuse of university computing resources or network accounts.",
    "# Process",
    "Reports are reviewed by the Office of Student Conduct. Students receive written notice,",
    "an opportunity to respond, and a written decision. Decisions may be appealed within 10",
    "business days to the Vice President for Student Affairs.",
    "Office of Student Conduct, Student Union 214, conduct@redwoodstate.example.edu",
  ]],
  ["academic-calendar-2026-27.pdf", "Academic Calendar 2026-2027", [
    "# Fall 2026",
    "Aug 24 ........ Instruction begins",
    "Sep 7 ......... Labor Day (campus closed)",
    "Sep 11 ........ Last day to add or drop without a W",
    "Nov 9 ......... Spring 2027 registration begins (by time ticket)",
    "Nov 11 ........ Veterans Day (campus closed)",
    "Nov 23-27 ..... Fall break",
    "Dec 11 ........ Last day of instruction",
    "Dec 14-18 ..... Final examinations",
    "# Spring 2027",
    "Jan 19 ........ Instruction begins",
    "Feb 5 ......... Last day to add or drop without a W",
    "Mar 22-26 ..... Spring break",
    "May 7 ......... Last day of instruction",
    "May 10-14 ..... Final examinations",
    "May 15 ........ Commencement",
    "Dates are subject to change. The online calendar is the official version.",
  ]],
  ["housing-contract-2026-27.pdf", "Residence Hall License Agreement 2026-2027", [
    "This agreement is between the student (Resident) and Redwood State University Housing &",
    "Residential Life. It covers the academic year from August 21, 2026 to May 15, 2027.",
    "# Rates (per semester)",
    "Madrone Hall, double room ........... $6,420.00",
    "Madrone Hall, single room ........... $7,480.00",
    "Redwood Commons, double room ........ $4,740.00",
    "Meal plans are required for all residence hall residents.",
    "# Cancellation",
    "Cancellations before July 1 receive a full refund less a $150 processing fee. After July 1,",
    "Residents are responsible for 50 percent of the fall semester rate.",
    "# Conduct and safety",
    "Residents agree to follow the Student Conduct Code and the Residential Life Handbook,",
    "including quiet hours (10 p.m. to 8 a.m. Sunday through Thursday) and fire safety rules.",
    "Housing & Residential Life, Madrone Hall 101, (707) 555-0131",
  ]],
  ["ferpa-annual-notice.pdf", "Annual Notification of Student Rights Under FERPA", [
    "The Family Educational Rights and Privacy Act (FERPA) gives students certain rights with",
    "respect to their education records. These rights include:",
    "1. The right to inspect and review education records within 45 days of a request.",
    "2. The right to request amendment of records the student believes are inaccurate.",
    "3. The right to provide written consent before the university discloses personally",
    "   identifiable information, except to the extent FERPA authorizes disclosure without consent.",
    "4. The right to file a complaint with the U.S. Department of Education.",
    "# Directory information",
    "Redwood State may release name, major, dates of attendance, degrees and awards, and",
    "participation in athletics without consent. Students may restrict release by filing a",
    "request with the Office of the Registrar.",
    "Office of the Registrar, Founders Hall 110, registrar@redwoodstate.example.edu",
  ]],
  ["benefits-summary-2026.pdf", "2026 Employee Benefits Summary", [
    "For benefits-eligible faculty and staff appointed at 50 percent time or more.",
    "# Medical (monthly employee contribution)",
    "Redwood Health Plan HMO .. Employee $0 | Employee + 1 $118 | Family $214",
    "Redwood Health Plan PPO .. Employee $86 | Employee + 1 $242 | Family $398",
    "# Dental and vision",
    "Coastal Dental Plan and ClearView Vision Plan coverage are free for employees and dependents.",
    "# Retirement",
    "State Public Employees' Retirement System pension; optional 403(b) and 457(b) plans.",
    "# Other benefits",
    "Life insurance (1x salary), long-term disability, employee assistance program, and a fee",
    "waiver for up to two courses per semester.",
    "Open enrollment: October 12-30, 2026. Human Resources, Founders Hall 230, (707) 555-0148.",
  ]],
  ["library-policies.pdf", "Sequoia Library Circulation Policies", [
    "# Loan periods",
    "Undergraduate students ...... 28 days, 3 renewals",
    "Graduate students ........... 90 days, 3 renewals",
    "Faculty and staff ........... One semester, unlimited renewals",
    "Course reserves ............. 2 hours or 1 day, in library use only",
    "Laptops and chargers ........ 4 hours",
    "# Fines and fees",
    "Overdue reserves: $1.00 per hour. Overdue laptops: $5.00 per hour, maximum $50.00.",
    "General collection items: $15.00 flat fee after 30 days overdue.",
    "Lost items are billed at replacement cost plus a $20.00 processing fee.",
    "# Conduct",
    "Quiet floors are 3 and 4. Group study rooms may be reserved for up to 3 hours per day.",
    "Access Services, Sequoia Library 1st floor, (707) 555-0125. Updated Spring 2019.",
  ]],
  ["emergency-guide.pdf", "Emergency Procedures Quick Guide", [
    "In any emergency, call 911. From a campus phone, dial 9-911. University Police: (707) 555-0199.",
    "# Fire",
    "Activate the nearest alarm, leave by the nearest exit, and do not use elevators.",
    "Meet at your building's evacuation assembly area.",
    "# Earthquake",
    "Drop, cover, and hold on. After shaking stops, evacuate if the building is damaged.",
    "# Tsunami (coastal field sites)",
    "If you feel a strong or long earthquake near the coast, move to high ground immediately.",
    "# Wildfire smoke",
    "Check RSU Alert messages. Stay indoors and use buildings with filtered air when AQI is above 150.",
    "# Shelter in place",
    "Go inside the nearest building, lock or barricade doors, silence phones, and wait for instructions.",
    "Sign up for RSU Alert text messages in RedwoodConnect under Profile.",
  ]],
  ["bsn-program-handbook-2025-26.pdf", "B.S.N. Program Student Handbook 2025-26", [
    "School of Nursing, College of Health Sciences. Salal Hall 210, (707) 555-0138.",
    "# Clinical requirements",
    "Students must hold current CPR (BLS) certification and clear a background check before clinicals.",
    "Immunization records are due to the clinical coordinator by August 1 each year.",
    "# Progression",
    "A grade of C (75%) or better is required in every NURS course. Two failed NURS courses result",
    "in dismissal from the program. Dosage calculation exams require 90% to pass.",
    "# Simulation Center",
    "Uniforms are required in the Simulation Center. Scenarios are recorded for debriefing only.",
  ]],
  ["first-gen-scholars-application-2026-27.pdf", "First-Generation Scholars Application 2026-27", [
    "Return to the Center for Student Success, Rowan Student Union 204, by November 20, 2026.",
    "# Eligibility",
    "Neither parent or guardian completed a four-year degree. Enrolled full time at Redwood State.",
    "# Application",
    "Name: ______________________   Student ID: ____________   Major: ______________________",
    "Expected graduation term: ____________   Email: ______________________@redwoodstate.example.edu",
    "In 250 words or less, describe a goal you hope to reach at Redwood State.",
    "# Program benefits",
    "Peer mentor, priority registration, a $500 book stipend, and a summer bridge program.",
  ]],
  ["logging-records-finding-aid.pdf", "Finding Aid: Arcadia Falls Lumber Company Records, 1902-1998", [
    "Sequoia Library Special Collections and University Archives. Collection MS-114.",
    "# Scope and content",
    "Payroll ledgers, mill production logs, correspondence, photographs, and maps documenting",
    "logging operations in the Arcadia Falls watershed.",
    "# Series",
    "Series 1: Payroll ledgers, 1902-1961 (48 volumes)",
    "Series 2: Mill production logs, 1910-1998 (112 boxes)",
    "Series 3: Photographs, 1905-1975 (2,300 prints and negatives)",
    "Series 4: Maps and survey plats, 1902-1988 (86 oversize folders)",
    "Access: open for research. Digitized series are available through the library catalog.",
  ]],
  ["mens-basketball-schedule-2026-27.pdf", "Redwood Owls Men's Basketball 2026-27 Schedule", [
    "Home games at Owl Arena. All times Pacific. Schedule subject to change.",
    "# November",
    "Tue Nov 3  at North Shore ................... 7:00 PM",
    "Fri Nov 6  vs. Cascade State (Home Opener) .. 7:00 PM",
    "Tue Nov 10 vs. Summit State ................. 7:00 PM",
    "Nov 26-28  Desert Palms Classic, Mirage Valley .. TBA",
    "# December",
    "Sat Dec 5  at Cedar Valley .................. 5:00 PM",
    "Sat Dec 19 vs. Division I opponent (TBA) .... 2:00 PM",
    "Student tickets are free with a valid RSU ID. Owls Ticket Office, (707) 555-0170.",
  ]],
  ["sleep-study-summary-2026.pdf", "Research Summary: Class Start Times and Student Sleep", [
    "Department of Psychology. Principal investigator: Rebecca Stein, Ph.D.",
    "# Summary",
    "Moving the earliest class start from 8:00 to 9:00 a.m. was associated with 38 more minutes",
    "of nightly sleep among participating first-year students (n = 412).",
    "# Method",
    "Participants wore wrist activity trackers for two weeks in Spring 2025 and two weeks in Fall 2025.",
    "# Limitations",
    "Participants volunteered; results may not generalize to all students.",
    "This summary is not a peer-reviewed publication.",
  ]],
  ["housing-rates-2026-27.pdf", "Residence Hall Rates 2026-27", [
    "Annual rates, including utilities and internet. Meal plans are billed separately.",
    "# Double / single room",
    "Madrone Hall (suite, first-year and Honors) ...... $11,640 / $13,920",
    "Redwood Commons, Cypress Hall (traditional) ...... $9,480 / $11,280",
    "Tanoak Village, Huckleberry Court (suite) ........ $10,380 / $12,300",
    "Silverfin Court, Spruce Grove Apartments ......... $10,920 / $12,960",
    "Alder Family Housing (2-bedroom) ................. $1,240 per month",
    "Rates are billed in two equal installments, fall and spring.",
    "Housing & Residential Life, Madrone Hall 101, (707) 555-0150.",
  ]],
];

const esc = (s: string) => s.replace(/[\\()]/g, (c) => `\\${c}`);

function pdf(title: string, lines: string[]): string {
  const ops = ["BT", "/F2 18 Tf", "72 720 Td", `(${esc(title)}) Tj`, "/F1 9 Tf", "0 -16 Td", "(Redwood State University - Arcadia Falls, California) Tj", "0 -12 Td"];
  for (const line of lines) {
    if (line.startsWith("# ")) ops.push("/F2 12 Tf", "0 -22 Td", `(${esc(line.slice(2))}) Tj`, "0 -4 Td");
    else ops.push("/F1 10 Tf", "0 -15 Td", `(${esc(line)}) Tj`);
  }
  ops.push("ET");
  const stream = ops.join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    `<< /Title (${esc(title)}) /Author (Redwood State University) /Producer (RSU Office Printer) >>`,
  ];
  let out = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, i) => { offsets.push(out.length); out += `${i + 1} 0 obj\n${body}\nendobj\n`; });
  const xref = out.length;
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.map((o) => `${String(o).padStart(10, "0")} 00000 n \n`).join("")}`;
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info 7 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return out;
}

mkdirSync(OUT, { recursive: true });
for (const [file, title, lines] of DOCS) writeFileSync(new URL(file, OUT), pdf(title, lines), "latin1");
console.log(`gen:docs: wrote ${DOCS.length} PDFs to public/documents/`);
