// Writes small one-page fake PDFs to public/documents/ (targets for "link to document" alerts).
// Hand-written PDF syntax, no dependencies. Run: npm run gen:docs
import { mkdirSync, writeFileSync } from "node:fs";

const OUT = new URL("../public/documents/", import.meta.url);

// [file, title, lines]; "# " marks a heading. ASCII only (standard Helvetica encoding).
const DOCS: [string, string, string[]][] = [
  ["tuition-schedule-2025-26.pdf", "2025-26 Tuition and Fee Schedule", [
    "Rates per semester, effective Fall 2025. Approved by the Board of Trustees, May 2025.",
    "# Undergraduate",
    "State tuition, 6.1 or more units .............. $2,946.00",
    "State tuition, 0 to 6.0 units ................. $1,710.00",
    "Nonresident tuition, per unit (added) ......... $396.00",
    "# Graduate",
    "State tuition, 6.1 or more units .............. $3,480.00",
    "State tuition, 0 to 6.0 units ................. $2,020.00",
    "# Mandatory campus fees (all students)",
    "Student Success Fee ........................... $498.00",
    "Health Services Fee ........................... $200.00",
    "Health Facilities Fee ......................... $11.00",
    "Associated Students Fee ....................... $99.00",
    "Rowan Student Union Fee ....................... $242.00",
    "Recreation Center Fee ......................... $173.00",
    "Instructionally Related Activities Fee ........ $92.00",
    "Technology Fee ................................ $41.00",
    "Fees are subject to change without notice. Course materials and lab fees are listed in the",
    "Class Schedule. Questions: Student Accounts, Founders Hall 140, (707) 555-0132.",
  ]],
  ["catalog-addendum-2025-26.pdf", "General Catalog 2025-2026 Addendum", [
    "This addendum updates the 2025-2026 General Catalog. It supersedes the printed catalog.",
    "# Changes to courses",
    "CS 304 Operating Systems: Prerequisite is now CS 201 only (CS 209 no longer required).",
    "MATH 119: Course retitled Statistics for Everyday Life (was Quantitative Reasoning).",
    "NURS 301: Clinical hours increased from 90 to 135; units unchanged.",
    "ENVS 301: New course, Wildfire and Forest Management (3 units).",
    "# Changes to programs",
    "B.S. Computer Science: CS 333 Accessible and Inclusive Software Design added as an",
    "upper-division core option beginning Fall 2026.",
    "M.B.A.: Capstone may be completed as a consulting project or a thesis.",
    "# Policy updates",
    "The deadline to drop without a W grade is now census, the end of the fourth week of instruction.",
    "Posted by the Office of the Registrar. Last revised August 12, 2025.",
  ]],
  ["parking-map.pdf", "Campus Parking Map and Permit Guide", [
    "Permits are required Monday through Friday, 7:00 a.m. to 10:00 p.m., in all campus lots.",
    "# Lots by permit type",
    "Lot A (Canopy Drive entrance) ........ Visitors (hourly and daily)",
    "Lot B (behind Founders Hall) ......... General (G), daily",
    "Lot C (Owl Arena) .................... General (G), daily, event parking",
    "Lot D (Redwood Field) ................ General (G)",
    "Lot F (Sequoia Engineering Hall) ..... General (G), Faculty/Staff (F)",
    "Lot J (upper campus, shuttle) ........ General (G)",
    "Lot M (Madrone Hall structure) ....... Madrone Hall residents (RM)",
    "Lots R1-R6 (residence halls) ......... Resident students (R)",
    "# Accessible parking",
    "Accessible spaces are in every lot. A state disabled placard plus any valid RSU permit",
    "is required. Van-accessible spaces: Lots A, B, C, and M.",
    "# Permit prices (per semester)",
    "General (G) $189.00 | Resident (R) $214.00 | Madrone Hall (RM) $246.00 | Motorcycle $48.00",
    "Faculty/Staff (F): $540.00 per year by payroll deduction.",
    "Parking & Transportation Services, Corporation Yard, (707) 555-0162.",
    "Note: this map is a text version. A graphical map is available at the Parking office.",
  ]],
  ["student-conduct-code.pdf", "Student Conduct Code", [
    "Executive Order SA-14. Revised July 2024.",
    "# Purpose",
    "Redwood State University is committed to a safe learning environment. This code describes",
    "the standards of conduct expected of students and the process for resolving alleged violations.",
    "# Prohibited conduct (summary)",
    "1. Academic dishonesty, including cheating, plagiarism, and unauthorized use of AI tools.",
    "2. Harassment, threats, or conduct that endangers the health or safety of any person.",
    "3. Theft of or damage to university or personal property.",
    "4. Unauthorized use of alcohol, cannabis, or other controlled substances on campus.",
    "5. Misuse of university computing resources or network accounts.",
    "# Process",
    "Reports are reviewed by the Office of Student Conduct. Students receive written notice,",
    "an opportunity to respond, and a written decision. Decisions may be appealed within 10",
    "business days to the Vice President for Student Affairs.",
    "Office of Student Conduct, Student Union 214, conduct@redwoodstate.edu",
  ]],
  ["academic-calendar-2026-27.pdf", "Academic Calendar 2026-2027", [
    "# Fall 2026",
    "Aug 24 ........ Instruction begins",
    "Sep 7 ......... Labor Day (campus closed)",
    "Aug 31 ........ Last day to add without a permission number",
    "Sep 18 ........ Census date (last day to drop without a W)",
    "Oct 23-25 ..... Homecoming & Family Weekend",
    "Nov 2 ......... Spring 2027 registration begins (by time ticket)",
    "Nov 6 ......... Last day to withdraw with a W",
    "Nov 11 ........ Veterans Day (campus closed)",
    "Nov 23-27 ..... Fall break",
    "Dec 11 ........ Last day of instruction",
    "Dec 14-18 ..... Final examinations",
    "Dec 19 ........ Winter Commencement, Owl Arena",
    "# Spring 2027",
    "Jan 18 ........ Martin Luther King Jr. Day (campus closed)",
    "Jan 20 ........ Instruction begins",
    "Feb 12 ........ Census date (last day to drop without a W)",
    "Mar 22-26 ..... Spring break",
    "Mar 31 ........ Cesar Chavez Day (campus closed)",
    "Apr 9 ......... Last day to withdraw with a W",
    "May 7 ......... Last day of instruction",
    "May 10-14 ..... Final examinations",
    "May 15-16 ..... Commencement, Redwood Field",
    "Dates are subject to change. The online calendar is the official version.",
  ]],
  ["housing-contract-2026-27.pdf", "Residence Hall License Agreement 2026-2027", [
    "This agreement is between the student (Resident) and Redwood State University Housing &",
    "Residential Life. It covers the academic year from August 21, 2026 to May 15, 2027.",
    "# Rates (per semester)",
    "Madrone Hall, double room ........... $5,820.00",
    "Madrone Hall, single room ........... $6,960.00",
    "Redwood Commons, double room ........ $4,740.00",
    "Meal plans are required for all residence hall residents.",
    "# Cancellation",
    "Cancellations before July 1 receive a full refund less a $150 processing fee. After July 1,",
    "Residents are responsible for 50 percent of the fall semester rate.",
    "# Conduct and safety",
    "Residents agree to follow the Student Conduct Code and the Residential Life Handbook,",
    "including quiet hours (10 p.m. to 8 a.m. Sunday through Thursday) and fire safety rules.",
    "Housing & Residential Life, Madrone Hall 101, (707) 555-0140",
  ]],
  ["ferpa-annual-notice.pdf", "Annual Notification of Student Rights Under FERPA", [
    "The Family Educational Rights and Privacy Act (FERPA) gives students certain rights with",
    "respect to their education records. These rights include:",
    "1. The right to inspect and review education records within 45 days of a request.",
    "2. The right to request amendment of records the student believes are inaccurate.",
    "3. The right to provide written consent before the university discloses personally",
    "   identifiable information, except to the extent FERPA authorizes disclosure without consent.",
    "4. The right to file a complaint with the U.S. Department of Education.",
    "# Directory information",
    "Redwood State may release name, major, dates of attendance, degrees and awards, and",
    "participation in athletics without consent. Students may restrict release by filing a",
    "request with the Office of the Registrar.",
    "Office of the Registrar, Founders Hall 130, registrar@redwoodstate.edu",
  ]],
  ["benefits-summary-2026.pdf", "2026 Employee Benefits Summary", [
    "For benefits-eligible faculty and staff appointed at 50 percent time or more.",
    "# Medical (monthly employee contribution)",
    "Canopy HMO ........................ Employee $0 | Employee + 1 $62 | Family $118",
    "North Coast PPO ................... Employee $84 | Employee + 1 $236 | Family $392",
    "Redwood Health Savings Plan ....... Employee $0 | Employee + 1 $0 | Family $38",
    "Redwood Health Plan (HMO) ......... Employee $0 | Employee + 1 $48 | Family $96",
    "# Dental and vision",
    "Coastal Dental Plan and ClearView Vision Plan coverage are free for employees and dependents.",
    "# Retirement",
    "State Public Employees' Retirement System pension; optional 403(b) and 457(b) plans.",
    "# Other benefits",
    "Life insurance (1x salary), long-term disability, employee assistance program, and a fee",
    "waiver for up to 6 units per semester.",
    "Open enrollment: October 12 - November 6, 2026. Human Resources, Founders Hall 210, (707) 555-0180.",
  ]],
  ["library-policies.pdf", "Sequoia Library Circulation Policies", [
    "# Loan periods",
    "Undergraduate students ...... 50 items, 28 days, 3 renewals",
    "Graduate students ........... 75 items, one semester, 3 renewals",
    "Faculty ..................... 150 items, academic year, unlimited renewals",
    "Staff ....................... 50 items, 56 days, 3 renewals",
    "Community borrowers ......... 10 items, 21 days, 1 renewal",
    "Course reserves ............. 2 items, 2 hours, in library use only",
    "# Fines and fees",
    "No overdue fines on regular loans. Course reserves: $1.00 per hour.",
    "Items 30 days overdue are billed as lost: $110.00 replacement plus $15.00 processing.",
    "# Conduct",
    "Covered drinks are permitted. Food is permitted on floors 1 and 2 only. Quiet floors are 3 and 4.",
    "Group study rooms may be reserved for up to 2 hours per day and 6 hours per week.",
    "Access Services, Sequoia Library 1st floor, (707) 555-0271. Revised Fall 2018.",
  ]],
  ["emergency-guide.pdf", "Emergency Procedures Quick Guide", [
    "In any emergency, call 911. From a campus phone, dial 9-911. University Police (non-emergency): (707) 555-0160.",
    "# Fire",
    "Activate the nearest alarm, leave by the nearest exit, and do not use elevators.",
    "Meet at your building's evacuation assembly area.",
    "# Earthquake",
    "Drop, cover, and hold on. After shaking stops, evacuate if the building is damaged.",
    "# Tsunami (coastal field sites)",
    "If you feel a strong or long earthquake near the coast, move to high ground immediately.",
    "# Wildfire smoke",
    "Check RSU Alert messages. Stay indoors and use buildings with filtered air when AQI is above 150.",
    "# Shelter in place",
    "Go inside the nearest building, lock or barricade doors, silence phones, and wait for instructions.",
    "Sign up for RSU Alert text messages in RedwoodConnect under Profile.",
  ]],
  ["bsn-program-handbook-2025-26.pdf", "B.S.N. Program Student Handbook 2025-26", [
    "School of Nursing, College of Health Sciences. Salal Hall 100, (707) 555-0138.",
    "# Clinical requirements",
    "Students must hold current CPR (BLS) certification and clear a background check before clinicals.",
    "Immunization records are due to the clinical coordinator by August 1 each year.",
    "# Progression",
    "A grade of C (75%) or better is required in every NURS course. Two failed NURS courses result",
    "in dismissal from the program. Dosage calculation exams require 90% to pass.",
    "# Nursing Simulation Center (Salal Hall)",
    "Uniforms are required in the Nursing Simulation Center. Scenarios are recorded for debriefing only.",
  ]],
  ["first-gen-scholars-application-2026-27.pdf", "First-Generation Scholars Application 2026-27", [
    "Return to the First-Generation Scholars office, Rowan Student Union 204, by November 15, 2026.",
    "# Eligibility",
    "Neither parent or guardian completed a four-year degree. Enrolled full time at Redwood State.",
    "# Application",
    "Name: ______________________   Student ID: ____________   Major: ______________________",
    "Expected graduation term: ____________   Email: ______________________@redwoodstate.edu",
    "In 250 words or less, describe a goal you hope to reach at Redwood State.",
    "# Program benefits",
    "Peer and faculty mentors, priority registration for two semesters, a $3,000 annual award, and summer bridge.",
  ]],
  ["logging-records-finding-aid.pdf", "Finding Aid: Arcadia Lumber Company Records, 1902-1958", [
    "Sequoia Library Special Collections and University Archives. Collection MS-114.",
    "# Scope and content",
    "Payroll ledgers, mill production logs, correspondence, photographs, and maps documenting",
    "logging operations in the Arcadia Falls watershed.",
    "# Series",
    "Series 1: Payroll ledgers, 1902-1958 (48 volumes)",
    "Series 2: Mill production logs, 1910-1958 (112 boxes)",
    "Series 3: Photographs, 1905-1958 (2,300 prints and negatives)",
    "Series 4: Maps and survey plats, 1902-1956 (86 oversize folders)",
    "Part of the Arcadia Falls Logging Records Digital Collection (1885-1985), which also includes",
    "records from three other timber companies, two unions, and the Arcadia Falls Oral History Project.",
    "Access: open for research. Digitized series are available through the library catalog.",
  ]],
  ["paccu-action-letter-2021.pdf", "PACCU Commission Action Letter", [
    "Pacific Accrediting Commission for Colleges and Universities (PACCU)",
    "400 Harbor Plaza, Suite 900, Westmere, CA",
    "July 9, 2021",
    "Elena Vasquez-Hart, Ph.D., President, Redwood State University",
    "# Commission action",
    "At its June 2021 meeting, the Commission reaffirmed the accreditation of Redwood State",
    "University for a period of ten years, following the Institutional Report and the spring 2021",
    "site visit. The next reaffirmation review is scheduled for 2030-31.",
    "# Required follow-up",
    "A Mid-Cycle Review is due in spring 2025, reporting on (1) equity gaps in graduation rates,",
    "(2) assessment of general education learning outcomes, and (3) long-term budget planning.",
    "# Commendations",
    "The Commission commends the university for place-based research that involves undergraduates",
    "and for its support of first-generation students.",
    "Questions: Office of Academic Planning and Assessment, (707) 555-0112.",
  ]],
  ["mens-basketball-schedule-2026-27.pdf", "Redwood Owls Men's Basketball 2026-27 Schedule", [
    "Home games at Owl Arena. All times Pacific. Schedule subject to change.",
    "# November",
    "Fri Nov 6  vs. Cascade State (Home Opener) .. 7:00 PM",
    "Mon Nov 9  vs. North Shore .................. 5:30 PM",
    "Thu Nov 12 at Granite Bluff ................. 7:00 PM",
    "Sun Nov 15 vs. North Shore .................. 7:00 PM",
    "Wed Nov 18 at Harbor Point * ................ 7:00 PM",
    "Sun Nov 22 at Cascade State * ............... 2:00 PM",
    "Wed Nov 25 vs. Westmere ..................... 2:00 PM",
    "Fri Nov 27 vs. Copper Creek State (Desert Palms Classic, Mirage Valley) .. 5:00 PM",
    "Sat Nov 28 vs. Juniper Valley (Desert Palms Classic, Mirage Valley) ...... 7:00 PM",
    "# December",
    "Wed Dec 2  at Summit State * ................ 2:00 PM",
    "Sat Dec 5  vs. Timberline * ................. 2:00 PM",
    "Sat Dec 12 at Stonebridge Tech * ............ 2:00 PM",
    "Wed Dec 16 at North Shore * ................. 2:00 PM",
    "Sat Dec 19 at Harbor Point * ................ 5:30 PM",
    "* Pacific North Conference game.",
    "Student tickets are free with a valid RSU ID. Owls Ticket Office, (707) 555-0165.",
  ]],
  ["sleep-study-summary-2026.pdf", "Research Summary: Class Start Times and Student Sleep", [
    "Department of Psychology. Principal investigator: Kwame Asante, Ph.D. Co-investigator: Isabel Moreno, Ph.D.",
    "# Summary",
    "Moving the earliest class start from 7:30 to 8:00 a.m. in Fall 2025 was associated with about",
    "24 more minutes of nightly sleep, better mood, and less daytime sleepiness among students.",
    "# Method",
    "Participants (312 in Spring 2025, before the change; 298 in Spring 2026, after it) wore wrist",
    "activity monitors for two weeks, kept sleep diaries, and completed daily phone surveys.",
    "# Limitations",
    "Participants volunteered; results may not generalize to all students.",
    "This summary is not a peer-reviewed publication.",
  ]],
  ["housing-rates-2026-27.pdf", "Residence Hall Rates 2026-27", [
    "Annual rates, including utilities and internet. Meal plans are billed separately.",
    "# Double / single room",
    "Madrone Hall (suite, first-year and Honors) ...... $11,640 / $13,920",
    "Redwood Commons, Cypress Hall (traditional) ...... $9,480 / $11,280",
    "Tanoak Village, Huckleberry Court (suite) ........ $10,380 / $12,300",
    "Fern Glen, Spruce Grove Apartments ............... $10,920 / $12,960",
    "Alder Family Housing (2-bedroom) ................. $1,240 per month",
    "Rates are billed in two equal installments, fall and spring.",
    "Housing & Residential Life, Madrone Hall 101, (707) 555-0140.",
  ]],
];

const esc = (s: string) => s.replace(/[\\()]/g, (c) => `\\${c}`);

function pdf(title: string, lines: string[]): string {
  const ops = ["BT", "/F2 18 Tf", "72 720 Td", `(${esc(title)}) Tj`, "/F1 9 Tf", "0 -16 Td", "(Redwood State University - Arcadia Falls, California) Tj", "0 -12 Td"];
  for (const line of lines) {
    if (line.startsWith("# ")) ops.push("/F2 12 Tf", "0 -22 Td", `(${esc(line.slice(2))}) Tj`, "0 -4 Td");
    else ops.push("/F1 10 Tf", "0 -15 Td", `(${esc(line)}) Tj`);
  }
  ops.push("ET");
  const stream = ops.join("\n");
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    `<< /Title (${esc(title)}) /Author (Redwood State University) /Producer (RSU Office Printer) >>`,
  ];
  let out = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((body, i) => { offsets.push(out.length); out += `${i + 1} 0 obj\n${body}\nendobj\n`; });
  const xref = out.length;
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.map((o) => `${String(o).padStart(10, "0")} 00000 n \n`).join("")}`;
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info 7 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return out;
}

mkdirSync(OUT, { recursive: true });
for (const [file, title, lines] of DOCS) writeFileSync(new URL(file, OUT), pdf(title, lines), "latin1");
console.log(`gen:docs: wrote ${DOCS.length} PDFs to public/documents/`);
